using backend.Extensions;
using backend.Middleware;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;

var builder = WebApplication.CreateBuilder(args);

// DigitalOcean App Platform & container port binding support (reads $PORT or configuration)
var port = Environment.GetEnvironmentVariable("PORT") ?? builder.Configuration["PORT"];
if (!string.IsNullOrEmpty(port))
{
    builder.WebHost.UseUrls($"http://0.0.0.0:{port}");
}

// 1. Add Controllers
builder.Services.AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase;
        options.JsonSerializerOptions.DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull;
    });

// 2. Add Layered Application Services & DbContext
builder.Services.AddApplicationServices(builder.Configuration);

// 3. Add JWT Authentication & Authorization
builder.Services.AddJwtAuthentication(builder.Configuration);
builder.Services.AddAuthorization();

// 4. Configure CORS
var allowedOrigins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>() 
                     ?? new[] { "http://localhost:5173", "http://localhost:3000" };

builder.Services.AddCors(options =>
{
    options.AddPolicy("DefaultCorsPolicy", policy =>
    {
        policy.WithOrigins(allowedOrigins)
              .AllowAnyHeader()
              .AllowAnyMethod()
              .AllowCredentials();
    });
});

// 5. Configure Swagger with JWT Bearer UI
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "NexusSales Platform API",
        Version = "v1",
        Description = "Customer Sales Executive Management Platform & Real-Time Calling Engine API"
    });

    c.CustomSchemaIds(type => type.FullName?.Replace("+", ".") ?? type.Name);

    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header using the Bearer scheme. Enter: Bearer {token}",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.ApiKey,
        Scheme = "Bearer"
    });

    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            Array.Empty<string>()
        }
    });
});

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var config = scope.ServiceProvider.GetRequiredService<IConfiguration>();
    var useInMemory = config.GetValue<bool>("UseInMemoryDatabase", false);
    var db = scope.ServiceProvider.GetRequiredService<backend.Data.ApplicationDbContext>();
    if (useInMemory)
    {
        db.Database.EnsureCreated();
    }
    else
    {
        try
        {
            var sql = @"
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Followups') THEN
                        ALTER TABLE ""Followups"" RENAME TO followups;
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Consultations') THEN
                        ALTER TABLE ""Consultations"" RENAME TO consultations;
                    END IF;
                    
                    CREATE TABLE IF NOT EXISTS followups (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""CompanyId"" integer NOT NULL,
                        ""AssignedAgentId"" integer NOT NULL DEFAULT 1,
                        ""InvestorId"" integer NULL,
                        ""ContactId"" character varying(100) NULL,
                        ""ContactType"" character varying(50) NOT NULL DEFAULT 'lead',
                        ""ContactName"" character varying(150) NOT NULL,
                        ""ContactPhone"" character varying(50) NOT NULL,
                        ""ScheduledAt"" timestamp with time zone NOT NULL,
                        ""Priority"" character varying(50) NOT NULL DEFAULT 'Medium',
                        ""Status"" character varying(50) NOT NULL DEFAULT 'Pending',
                        ""Notes"" text NOT NULL DEFAULT '',
                        ""Agenda"" text NULL,
                        ""OutcomeNotes"" text NULL,
                        ""AssignedToName"" text NOT NULL DEFAULT '',
                        ""AssignedToRole"" text NOT NULL DEFAULT '',
                        ""InvestorName"" text NULL,
                        ""CompletedAt"" timestamp with time zone NULL,
                        ""RescheduledTo"" timestamp with time zone NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                        ""UpdatedAt"" timestamp with time zone NULL
                    );

                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'followups' AND column_name = 'AssignedToId') THEN
                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'followups' AND column_name = 'AssignedAgentId') THEN
                            ALTER TABLE followups RENAME COLUMN ""AssignedToId"" TO ""AssignedAgentId"";
                        END IF;
                    END IF;

                    ALTER TABLE followups ADD COLUMN IF NOT EXISTS ""ContactType"" character varying(50) NOT NULL DEFAULT 'lead';
                    ALTER TABLE followups ADD COLUMN IF NOT EXISTS ""Priority"" character varying(50) NOT NULL DEFAULT 'Medium';
                    ALTER TABLE followups ADD COLUMN IF NOT EXISTS ""Notes"" text NOT NULL DEFAULT '';
                    ALTER TABLE followups ADD COLUMN IF NOT EXISTS ""Agenda"" text NULL;
                    ALTER TABLE followups ADD COLUMN IF NOT EXISTS ""OutcomeNotes"" text NULL;
                    ALTER TABLE followups ADD COLUMN IF NOT EXISTS ""AssignedToName"" text NOT NULL DEFAULT '';
                    ALTER TABLE followups ADD COLUMN IF NOT EXISTS ""AssignedToRole"" text NOT NULL DEFAULT '';
                    ALTER TABLE followups ADD COLUMN IF NOT EXISTS ""InvestorName"" text NULL;
                    ALTER TABLE followups ADD COLUMN IF NOT EXISTS ""CompletedAt"" timestamp with time zone NULL;
                    ALTER TABLE followups ADD COLUMN IF NOT EXISTS ""RescheduledTo"" timestamp with time zone NULL;
                    ALTER TABLE followups ADD COLUMN IF NOT EXISTS ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW();
                    ALTER TABLE followups ADD COLUMN IF NOT EXISTS ""UpdatedAt"" timestamp with time zone NULL;
                    ALTER TABLE followups ADD COLUMN IF NOT EXISTS ""AssignedAgentId"" integer NOT NULL DEFAULT 1;

                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'followups' AND column_name = 'Status' AND data_type = 'integer') THEN
                        ALTER TABLE followups ALTER COLUMN ""Status"" TYPE character varying(50) USING CASE WHEN ""Status"" = 1 THEN 'Completed' WHEN ""Status"" = 2 THEN 'Cancelled' WHEN ""Status"" = 3 THEN 'Rescheduled' ELSE 'Pending' END;
                    END IF;
                    ALTER TABLE followups ALTER COLUMN ""Status"" DROP NOT NULL;
                    ALTER TABLE followups ALTER COLUMN ""Status"" SET DEFAULT 'Pending';
                    ALTER TABLE followups ALTER COLUMN ""Priority"" DROP NOT NULL;
                    ALTER TABLE followups ALTER COLUMN ""Priority"" SET DEFAULT 'Medium';

                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'consultations') THEN
                        ALTER TABLE consultations ALTER COLUMN ""InvestorId"" DROP NOT NULL;
                    END IF;
                END $$;
            ";
            db.Database.ExecuteSqlRaw(sql);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[Database Init Warning] {ex.Message}");
        }

        // Patch: ensure tenants have EnabledFeatures populated
        try
        {
            var tenants = db.Tenants.ToList();
            bool patched = false;
            foreach (var t in tenants)
            {
                if (t.EnabledFeatures == null || t.EnabledFeatures.Count == 0)
                {
                    if (t.Slug == "ghl")
                    {
                        t.EnabledFeatures = new List<string>
                        {
                            "leads", "customers", "deals", "followups", "calls", "call-recording",
                            "call-transcription", "investors", "consultations", "investment-opportunities",
                            "reports", "users", "roles", "company-settings", "audit-logs"
                        };
                        patched = true;
                    }
                    else if (t.Slug == "jamin")
                    {
                        t.EnabledFeatures = new List<string>
                        {
                            "leads", "customers", "deals", "followups", "calls", "call-recording",
                            "call-transcription", "properties", "site-visits", "bookings",
                            "reports", "users", "roles", "company-settings", "audit-logs"
                        };
                        patched = true;
                    }
                }
            }
            if (patched) db.SaveChanges();
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[Tenant Feature Patch Warning] {ex.Message}");
        }

        // Patch: ensure roles have Permissions populated
        try
        {
            var allRoles = db.Roles.ToList();
            bool rolePatched = false;
            var allPerms = new[] {
                "leads.view","leads.create","leads.update","leads.delete","leads.assign","leads.export","leads.import","leads.convert",
                "customers.view","customers.create","customers.update","customers.delete",
                "deals.view","deals.create","deals.update","deals.delete",
                "calls.make","calls.receive","calls.view","calls.recordings.play",
                "followups.view","followups.create","followups.update",
                "properties.view","properties.update","site-visits.view","site-visits.create","bookings.view","bookings.create",
                "investors.view","investors.create","investors.update",
                "consultations.view","consultations.create","consultations.update",
                "opportunities.view","opportunities.create","opportunities.update",
                "reports.view","reports.export",
                "users.view","users.manage","roles.view","settings.view","settings.update","audit.view",
                "chat.view","chat.send","kyc.view","kyc.approve"
            };
            foreach (var role in allRoles)
            {
                if (role.Permissions == null || role.Permissions.Count == 0)
                {
                    if (role.Code == "super_admin" || role.Code == "company_admin")
                        role.Permissions = allPerms.ToList();
                    else if (role.Code == "irm")
                        role.Permissions = new List<string> {
                            "leads.view","leads.create","investors.view","investors.create","investors.update",
                            "consultations.view","consultations.create","consultations.update",
                            "opportunities.view","opportunities.create","opportunities.update",
                            "calls.make","calls.receive","calls.view","reports.view","chat.view","chat.send"
                        };
                    else // sales_executive
                        role.Permissions = new List<string> {
                            "leads.view","leads.create","leads.update","leads.convert",
                            "customers.view","customers.create","customers.update",
                            "deals.view","deals.create","deals.update",
                            "calls.make","calls.receive","calls.view",
                            "followups.view","followups.create","followups.update","chat.view","chat.send"
                        };
                    rolePatched = true;
                }
            }
            if (rolePatched) db.SaveChanges();
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[Role Permissions Patch Warning] {ex.Message}");
        }

        // Inbuilt lead seeding removed: all leads come from DB via API / frontend creation.
    }
}

// Global Exception Handling Middleware
app.UseMiddleware<ExceptionHandlingMiddleware>();

// Configure Swagger
app.UseSwagger();
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "NexusSales API v1");
    c.RoutePrefix = "swagger";
});

if (app.Environment.IsDevelopment())
{
    // Automatically open Swagger in default browser on startup
    app.Lifetime.ApplicationStarted.Register(() =>
    {
        var address = app.Urls.FirstOrDefault() ?? "http://localhost:5106";
        var swaggerUrl = $"{address.TrimEnd('/')}/swagger";
        try
        {
            System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
            {
                FileName = swaggerUrl,
                UseShellExecute = true
            });
        }
        catch { }
    });
}

app.UseCors("DefaultCorsPolicy");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();
