const { Client } = require('pg');

async function main() {
  const client = new Client({
    connectionString: 'postgres://neondb_owner:npg_wIWrXLJV9fF3@ep-sparkling-leaf-b3evey2y.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require'
  });

  await client.connect();
  console.log('=== 1. CHECKING JAMIN_BOOKINGS COLUMNS ===');
  const bkgColsRes = await client.query(`
    SELECT column_name, data_type, is_nullable, column_default
    FROM information_schema.columns 
    WHERE table_name = 'jamin_bookings'
    ORDER BY ordinal_position;
  `);
  const bkgCols = bkgColsRes.rows.map(r => r.column_name);
  console.log('Columns in jamin_bookings:', bkgCols.join(', '));
  
  const expectedCols = [
    'PaymentStatus', 'HoldExpiresAt', 'BasePrice', 'DevelopmentCharges', 
    'ApprovedDiscounts', 'CancelledAt', 'CancelledByUserId', 'CancelledByName', 
    'CancellationReason', 'RefundAmount'
  ];
  const missingCols = expectedCols.filter(c => !bkgCols.includes(c));
  console.log('Missing expected columns in jamin_bookings:', missingCols.length === 0 ? 'NONE (All present!)' : missingCols);

  console.log('\n=== 2. CHECKING JAMIN_PAYMENTS TABLE ===');
  const paymentsTableRes = await client.query(`
    SELECT EXISTS (
      SELECT 1 FROM information_schema.tables 
      WHERE table_schema = 'public' AND table_name = 'jamin_payments'
    );
  `);
  console.log('Does jamin_payments table exist?', paymentsTableRes.rows[0].exists);

  if (paymentsTableRes.rows[0].exists) {
    const payColsRes = await client.query(`
      SELECT column_name, data_type, is_nullable, column_default
      FROM information_schema.columns 
      WHERE table_name = 'jamin_payments'
      ORDER BY ordinal_position;
    `);
    console.log('Columns in jamin_payments:', payColsRes.rows.map(r => `${r.column_name} (${r.data_type})`).join(', '));
  }

  console.log('\n=== 3. CHECKING INDEXES ON JAMIN_BOOKINGS ===');
  const idxRes = await client.query(`
    SELECT indexname, indexdef 
    FROM pg_indexes 
    WHERE tablename = 'jamin_bookings';
  `);
  console.log('Indexes on jamin_bookings:');
  for (const row of idxRes.rows) {
    console.log(`- ${row.indexname}: ${row.indexdef}`);
  }

  console.log('\n=== 4. RUNNING SCHEMA PATCHES IF ANY MISSING (SAFE / IDEMPOTENT) ===');
  // Run Program.cs startup schema patches to ensure database matches active code perfectly
  await client.query(`ALTER TABLE IF EXISTS jamin_bookings ADD COLUMN IF NOT EXISTS "PaymentStatus" VARCHAR(50) NOT NULL DEFAULT 'Pending';`);
  await client.query(`ALTER TABLE IF EXISTS jamin_bookings ADD COLUMN IF NOT EXISTS "HoldExpiresAt" timestamp with time zone;`);
  await client.query(`ALTER TABLE IF EXISTS jamin_bookings ADD COLUMN IF NOT EXISTS "BasePrice" numeric(18,2) NOT NULL DEFAULT 0;`);
  await client.query(`ALTER TABLE IF EXISTS jamin_bookings ADD COLUMN IF NOT EXISTS "DevelopmentCharges" numeric(18,2) NOT NULL DEFAULT 0;`);
  await client.query(`ALTER TABLE IF EXISTS jamin_bookings ADD COLUMN IF NOT EXISTS "ApprovedDiscounts" numeric(18,2) NOT NULL DEFAULT 0;`);
  await client.query(`ALTER TABLE IF EXISTS jamin_bookings ADD COLUMN IF NOT EXISTS "CancelledAt" timestamp with time zone;`);
  await client.query(`ALTER TABLE IF EXISTS jamin_bookings ADD COLUMN IF NOT EXISTS "CancelledByUserId" integer;`);
  await client.query(`ALTER TABLE IF EXISTS jamin_bookings ADD COLUMN IF NOT EXISTS "CancelledByName" VARCHAR(150);`);
  await client.query(`ALTER TABLE IF EXISTS jamin_bookings ADD COLUMN IF NOT EXISTS "CancellationReason" VARCHAR(2000);`);
  await client.query(`ALTER TABLE IF EXISTS jamin_bookings ADD COLUMN IF NOT EXISTS "RefundAmount" numeric(18,2) NOT NULL DEFAULT 0;`);

  await client.query(`
    DO $$ BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_schema = 'public' AND table_name = 'jamin_bookings' AND constraint_name = 'FK_jamin_bookings_users_CancelledByUserId'
      ) THEN
        ALTER TABLE jamin_bookings ADD CONSTRAINT "FK_jamin_bookings_users_CancelledByUserId" 
          FOREIGN KEY ("CancelledByUserId") REFERENCES users ("Id") ON DELETE SET NULL;
      END IF;
    END $$;
  `);

  await client.query(`
    CREATE TABLE IF NOT EXISTS jamin_payments (
      "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "CompanyId" integer NOT NULL,
      "BookingId" integer NOT NULL,
      "CustomerId" integer,
      "LeadId" integer,
      "Amount" numeric(18,2) NOT NULL,
      "PaymentType" character varying(50) NOT NULL DEFAULT 'Token',
      "PaymentMode" character varying(100) NOT NULL DEFAULT 'Bank Transfer / NEFT',
      "TransactionReference" character varying(200) NOT NULL DEFAULT '',
      "Status" character varying(50) NOT NULL DEFAULT 'Pending',
      "VerifiedAt" timestamp with time zone,
      "VerifiedByUserId" integer,
      "VerifiedByName" character varying(150),
      "ReceiptNumber" character varying(100),
      "Notes" character varying(2000),
      "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
      "UpdatedAt" timestamp with time zone,
      CONSTRAINT "FK_jamin_payments_tenants_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES tenants ("Id") ON DELETE CASCADE,
      CONSTRAINT "FK_jamin_payments_jamin_bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES jamin_bookings ("Id") ON DELETE RESTRICT,
      CONSTRAINT "FK_jamin_payments_customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES customers ("Id") ON DELETE SET NULL,
      CONSTRAINT "FK_jamin_payments_leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES leads ("Id") ON DELETE SET NULL,
      CONSTRAINT "FK_jamin_payments_users_VerifiedByUserId" FOREIGN KEY ("VerifiedByUserId") REFERENCES users ("Id") ON DELETE SET NULL
    );
  `);

  await client.query(`CREATE INDEX IF NOT EXISTS "IX_jamin_payments_BookingId" ON jamin_payments ("BookingId");`);
  await client.query(`CREATE INDEX IF NOT EXISTS "IX_jamin_payments_CustomerId" ON jamin_payments ("CustomerId");`);
  await client.query(`CREATE INDEX IF NOT EXISTS "IX_jamin_payments_LeadId" ON jamin_payments ("LeadId");`);
  await client.query(`CREATE INDEX IF NOT EXISTS "IX_jamin_payments_Status" ON jamin_payments ("Status");`);

  // Ensure Partial Unique Index is created with reconciled statuses
  await client.query(`
    DO $$ BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_indexes 
        WHERE schemaname = 'public' AND tablename = 'jamin_bookings' AND indexname = 'IX_jamin_bookings_CompanyId_PlotId_Active'
      ) THEN
        IF NOT EXISTS (
          SELECT 1 FROM (
            SELECT "CompanyId", "PlotId" 
            FROM jamin_bookings 
            WHERE "PlotId" IS NOT NULL 
              AND "Status" IN ('Hold', 'Pending Verification', 'Booking Pending Verification', 'Token Paid', 'Token Verified', 'Agreement Signed', 'Registration Completed')
            GROUP BY "CompanyId", "PlotId" 
            HAVING COUNT(*) > 1
          ) dupes
        ) THEN
          CREATE UNIQUE INDEX "IX_jamin_bookings_CompanyId_PlotId_Active" 
          ON jamin_bookings ("CompanyId", "PlotId") 
          WHERE "PlotId" IS NOT NULL AND "Status" IN ('Hold', 'Pending Verification', 'Booking Pending Verification', 'Token Paid', 'Token Verified', 'Agreement Signed', 'Registration Completed');
        ELSE
          CREATE INDEX "IX_jamin_bookings_CompanyId_PlotId_Active" 
          ON jamin_bookings ("CompanyId", "PlotId") 
          WHERE "PlotId" IS NOT NULL AND "Status" IN ('Hold', 'Pending Verification', 'Booking Pending Verification', 'Token Paid', 'Token Verified', 'Agreement Signed', 'Registration Completed');
        END IF;
      END IF;
    END $$;
  `);

  console.log('\n=== 5. VERIFYING PARTIAL UNIQUE INDEX BEHAVIOR (DOUBLE-BOOKING TEST) ===');
  // Find a test plot or use transaction rollback
  const plotRes = await client.query(`SELECT "Id", "PlotNumber", "Status" FROM jamin_plots WHERE "CompanyId" = 2 LIMIT 1;`);
  if (plotRes.rows.length > 0) {
    const testPlot = plotRes.rows[0];
    console.log(`Testing concurrency / double booking protection on Plot ID ${testPlot.Id} (${testPlot.PlotNumber})...`);

    await client.query('BEGIN;');
    try {
      // Insert first active booking for test plot
      const b1 = await client.query(`
        INSERT INTO jamin_bookings ("CompanyId", "PlotId", "CustomerName", "CustomerPhone", "Status", "PaymentStatus", "TotalPlotPrice", "TokenAmountPaid", "BookingDate", "CreatedAt")
        VALUES (2, $1, 'Test Buyer A', '+919999900001', 'Pending Verification', 'Pending', 2500000, 100000, NOW(), NOW())
        RETURNING "Id";
      `, [testPlot.Id]);
      console.log(`- Inserted test booking 1 (ID: ${b1.rows[0].Id}) with Status 'Pending Verification'`);

      let duplicateCaught = false;
      try {
        // Attempt to insert second active booking for the SAME plot
        await client.query(`
          INSERT INTO jamin_bookings ("CompanyId", "PlotId", "CustomerName", "CustomerPhone", "Status", "PaymentStatus", "TotalPlotPrice", "TokenAmountPaid", "BookingDate", "CreatedAt")
          VALUES (2, $1, 'Test Buyer B', '+919999900002', 'Hold', 'Pending', 2500000, 100000, NOW(), NOW())
          RETURNING "Id";
        `, [testPlot.Id]);
      } catch (dupErr) {
        duplicateCaught = true;
        console.log(`- Duplicate booking correctly PREVENTED by partial unique index! Error: ${dupErr.message}`);
      }

      if (!duplicateCaught) {
        console.warn('- WARNING: Duplicate booking was NOT prevented by index!');
      } else {
        console.log('- SUCCESS: Double booking active conflict prevented by database unique index constraint!');
      }
    } finally {
      // ALWAYS ROLLBACK TEST TRANSACTION TO KEEP EXISTING DATA UNCHANGED
      await client.query('ROLLBACK;');
      console.log('- Test transaction rolled back. Existing data unchanged.');
    }
  }

  console.log('\n=== 6. VERIFYING EXISTING ACTIVE BOOKINGS DATA ===');
  const existingBookings = await client.query(`
    SELECT "Id", "PlotId", "PlotNumber", "CustomerName", "Status", "PaymentStatus", "TotalPlotPrice", "TokenAmountPaid"
    FROM jamin_bookings
    WHERE "CompanyId" = 2
    ORDER BY "Id" DESC
    LIMIT 5;
  `);
  console.log(`Found ${existingBookings.rows.length} existing bookings in Jamin Bazaar:`, existingBookings.rows);

  await client.end();
  console.log('\nAll schema verification checks completed successfully.');
}

main().catch(err => {
  console.error('Schema verification error:', err);
  process.exit(1);
});
