using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations;

[DbContext(typeof(backend.Data.ApplicationDbContext))]
[Migration("20260929130000_AddJaminPropertyInventory")]
public sealed class AddJaminPropertyInventory : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS jamin_projects (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""CompanyId"" integer NOT NULL,
                ""Name"" character varying(200) NOT NULL,
                ""Location"" character varying(300) NOT NULL,
                ""Status"" character varying(50) NOT NULL DEFAULT 'Active',
                ""Description"" character varying(2000) NOT NULL,
                ""TotalPlots"" integer NOT NULL,
                ""AvailablePlots"" integer NOT NULL,
                ""BookedPlots"" integer NOT NULL,
                ""PriceRange"" character varying(100) NOT NULL,
                ""ImageUrl"" character varying(500),
                ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                ""UpdatedAt"" timestamp with time zone,
                CONSTRAINT ""FK_jamin_projects_tenants_CompanyId"" FOREIGN KEY (""CompanyId"") REFERENCES tenants (""Id"") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS jamin_plots (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""CompanyId"" integer NOT NULL,
                ""ProjectId"" integer NOT NULL,
                ""PlotNumber"" character varying(100) NOT NULL,
                ""Dimensions"" character varying(50) NOT NULL,
                ""AreaSqFt"" integer NOT NULL,
                ""Facing"" character varying(50) NOT NULL,
                ""Status"" character varying(50) NOT NULL DEFAULT 'Available',
                ""Price"" numeric(18,2) NOT NULL,
                ""HeldByCustomerName"" character varying(150),
                ""HeldByCustomerPhone"" character varying(50),
                ""HoldExpiresAt"" timestamp with time zone,
                ""Notes"" character varying(2000),
                ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                ""UpdatedAt"" timestamp with time zone,
                CONSTRAINT ""FK_jamin_plots_tenants_CompanyId"" FOREIGN KEY (""CompanyId"") REFERENCES tenants (""Id"") ON DELETE CASCADE,
                CONSTRAINT ""FK_jamin_plots_jamin_projects_ProjectId"" FOREIGN KEY (""ProjectId"") REFERENCES jamin_projects (""Id"") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS jamin_bookings (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""CompanyId"" integer NOT NULL,
                ""ProjectId"" integer,
                ""PlotId"" integer,
                ""CustomerName"" character varying(150) NOT NULL,
                ""CustomerPhone"" character varying(50) NOT NULL,
                ""ProjectName"" character varying(200) NOT NULL,
                ""PlotNumber"" character varying(100) NOT NULL,
                ""TotalPlotPrice"" numeric(18,2) NOT NULL,
                ""TokenAmountPaid"" numeric(18,2) NOT NULL,
                ""PaymentMode"" character varying(100) NOT NULL,
                ""Status"" character varying(50) NOT NULL DEFAULT 'Token Paid',
                ""BookingDate"" timestamp with time zone NOT NULL,
                ""AssignedAgentId"" integer,
                ""AssignedAgentName"" character varying(150) NOT NULL,
                ""Notes"" character varying(2000),
                ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                ""UpdatedAt"" timestamp with time zone,
                CONSTRAINT ""FK_jamin_bookings_tenants_CompanyId"" FOREIGN KEY (""CompanyId"") REFERENCES tenants (""Id"") ON DELETE CASCADE,
                CONSTRAINT ""FK_jamin_bookings_jamin_projects_ProjectId"" FOREIGN KEY (""ProjectId"") REFERENCES jamin_projects (""Id"") ON DELETE SET NULL,
                CONSTRAINT ""FK_jamin_bookings_jamin_plots_PlotId"" FOREIGN KEY (""PlotId"") REFERENCES jamin_plots (""Id"") ON DELETE SET NULL,
                CONSTRAINT ""FK_jamin_bookings_users_AssignedAgentId"" FOREIGN KEY (""AssignedAgentId"") REFERENCES users (""Id"") ON DELETE SET NULL
            );

            CREATE INDEX IF NOT EXISTS ""IX_jamin_projects_CompanyId_Status"" ON jamin_projects (""CompanyId"", ""Status"");
            CREATE INDEX IF NOT EXISTS ""IX_jamin_plots_CompanyId_ProjectId_Status"" ON jamin_plots (""CompanyId"", ""ProjectId"", ""Status"");
            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_jamin_plots_ProjectId_PlotNumber"" ON jamin_plots (""ProjectId"", ""PlotNumber"");
            CREATE INDEX IF NOT EXISTS ""IX_jamin_bookings_CompanyId_Status"" ON jamin_bookings (""CompanyId"", ""Status"");
            CREATE INDEX IF NOT EXISTS ""IX_jamin_bookings_CustomerPhone"" ON jamin_bookings (""CustomerPhone"");
            CREATE INDEX IF NOT EXISTS ""IX_jamin_bookings_ProjectId"" ON jamin_bookings (""ProjectId"");
            CREATE INDEX IF NOT EXISTS ""IX_jamin_bookings_PlotId"" ON jamin_bookings (""PlotId"");
            CREATE INDEX IF NOT EXISTS ""IX_jamin_bookings_AssignedAgentId"" ON jamin_bookings (""AssignedAgentId"");
        ");
    }


    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "jamin_bookings");
        migrationBuilder.DropTable(name: "jamin_plots");
        migrationBuilder.DropTable(name: "jamin_projects");
    }
}
