import { CustomFieldDefinition } from '../types';

export const DEFAULT_CUSTOM_FIELD_DEFINITIONS: CustomFieldDefinition[] = [
  // GHL India Ventures - Leads
  {
    id: 'cf-ghl-lead-1',
    companyId: 't-ghl-01',
    module: 'leads',
    fieldKey: 'investmentCapacity',
    label: 'Investment Capacity',
    fieldType: 'select',
    required: false,
    options: ['₹50L - ₹1 Cr', '₹75L - ₹1.5 Cr', '₹1 Cr - ₹3 Cr', '₹1.5 Cr - ₹3 Cr', '₹3 Cr - ₹5 Cr', '₹5 Cr+'],
    defaultValue: '₹1 Cr - ₹3 Cr',
    displayOrder: 1,
    active: true,
  },
  {
    id: 'cf-ghl-lead-2',
    companyId: 't-ghl-01',
    module: 'leads',
    fieldKey: 'preferredAssetClass',
    label: 'Preferred Asset Class',
    fieldType: 'select',
    required: false,
    options: ['Commercial Pre-Leased', 'Commercial REIT / Pre-Leased', 'Industrial Logistics Park', 'Commercial Yield Funds'],
    defaultValue: 'Commercial Pre-Leased',
    displayOrder: 2,
    active: true,
  },
  {
    id: 'cf-ghl-lead-3',
    companyId: 't-ghl-01',
    module: 'leads',
    fieldKey: 'horizon',
    label: 'Investment Horizon',
    fieldType: 'text',
    required: false,
    defaultValue: '3-5 Years',
    displayOrder: 3,
    active: true,
  },

  // Jamin Bazaar - Leads
  {
    id: 'cf-jam-lead-1',
    companyId: 't-jamin-02',
    module: 'leads',
    fieldKey: 'budgetRange',
    label: 'Plot Budget Range',
    fieldType: 'select',
    required: false,
    options: ['₹25L - ₹45L', '₹45L - ₹65L', '₹65L - ₹90L', '₹80L - ₹1.1 Cr', '₹90L+'],
    defaultValue: '₹45L - ₹65L',
    displayOrder: 1,
    active: true,
  },
  {
    id: 'cf-jam-lead-2',
    companyId: 't-jamin-02',
    module: 'leads',
    fieldKey: 'preferredLocation',
    label: 'Preferred Micro-Market',
    fieldType: 'select',
    required: false,
    options: ['Devanahalli North', 'Sarjapur East', 'Mysore Highway Corridor', 'Airport Corridor North'],
    defaultValue: 'Devanahalli North',
    displayOrder: 2,
    active: true,
  },
  {
    id: 'cf-jam-lead-3',
    companyId: 't-jamin-02',
    module: 'leads',
    fieldKey: 'readyToRegister',
    label: 'Ready to Register',
    fieldType: 'text',
    required: false,
    defaultValue: 'Within 30 Days',
    displayOrder: 3,
    active: true,
  },

  // GHL India Ventures - Customers
  {
    id: 'cf-ghl-cust-1',
    companyId: 't-ghl-01',
    module: 'customers',
    fieldKey: 'investorType',
    label: 'Investor Type',
    fieldType: 'text',
    required: false,
    defaultValue: '',
    displayOrder: 1,
    active: true,
  },
  {
    id: 'cf-ghl-cust-2',
    companyId: 't-ghl-01',
    module: 'customers',
    fieldKey: 'totalAUMCommitted',
    label: 'Total AUM Committed',
    fieldType: 'text',
    required: false,
    defaultValue: '',
    displayOrder: 2,
    active: true,
  },
  {
    id: 'cf-ghl-cust-3',
    companyId: 't-ghl-01',
    module: 'customers',
    fieldKey: 'relationshipManager',
    label: 'Relationship Manager',
    fieldType: 'text',
    required: false,
    defaultValue: '',
    displayOrder: 3,
    active: true,
  },

  // Jamin Bazaar - Customers
  {
    id: 'cf-jam-cust-1',
    companyId: 't-jamin-02',
    module: 'customers',
    fieldKey: 'preferredPaymentBank',
    label: 'Preferred Payment Bank',
    fieldType: 'text',
    required: false,
    defaultValue: '',
    displayOrder: 1,
    active: true,
  },
  {
    id: 'cf-jam-cust-2',
    companyId: 't-jamin-02',
    module: 'customers',
    fieldKey: 'advocateAssigned',
    label: 'Advocate Assigned',
    fieldType: 'text',
    required: false,
    defaultValue: '',
    displayOrder: 2,
    active: true,
  },
];
