import { Tenant } from '../types';
import { FEATURES } from './features';

export const DEFAULT_TENANTS: Record<string, Tenant> = {
  ghl: {
    id: 't-ghl-01',
    name: 'GHL India Ventures',
    slug: 'ghl',
    brandColor: '#ef4444',
    logo: '/og-image -GHL Ventures.png',
    tagline: 'Institutional Wealth & Real Estate Investment Advisory',
    enabledFeatures: [
      FEATURES.LEADS,
      FEATURES.CUSTOMERS,
      FEATURES.DEALS,
      FEATURES.FOLLOWUPS,
      FEATURES.CALLS,
      FEATURES.CALL_RECORDING,
      FEATURES.CALL_TRANSCRIPTION,
      FEATURES.INVESTORS,
      FEATURES.CONSULTATIONS,
      FEATURES.INVESTMENT_OPPORTUNITIES,
      FEATURES.REPORTS,
      FEATURES.USERS,
      FEATURES.ROLES,
      FEATURES.COMPANY_SETTINGS,
      FEATURES.AUDIT_LOGS,
      FEATURES.CHAT,
    ],
    timezone: 'Asia/Kolkata (IST)',
    currency: '₹ INR',
    businessHours: '09:30 AM - 07:00 PM IST',
    status: 'Active',
  },
  jamin: {
    id: 't-jamin-02',
    name: 'Jamin Bazaar',
    slug: 'jamin',
    brandColor: '#e10600',
    logo: '/jamin-logo.png',
    tagline: 'Premium Plotted Enclaves & Farmland Communities',
    enabledFeatures: [
      FEATURES.LEADS,
      FEATURES.CUSTOMERS,
      FEATURES.DEALS,
      FEATURES.FOLLOWUPS,
      FEATURES.CALLS,
      FEATURES.CALL_RECORDING,
      FEATURES.CALL_TRANSCRIPTION,
      FEATURES.PROPERTIES,
      FEATURES.SITE_VISITS,
      FEATURES.BOOKINGS,
      FEATURES.REPORTS,
      FEATURES.USERS,
      FEATURES.ROLES,
      FEATURES.COMPANY_SETTINGS,
      FEATURES.AUDIT_LOGS,
      FEATURES.CHAT,
    ],
    timezone: 'Asia/Kolkata (IST)',
    currency: '₹ INR',
    businessHours: '09:00 AM - 06:30 PM IST',
    status: 'Active',
  },
};
