export {
  TENANTS,
  ROLES,
  USERS,
  INITIAL_LEADS,
  INITIAL_CUSTOMERS,
  INITIAL_DEALS,
  INITIAL_CALLS,
  INITIAL_FOLLOWUPS,
  INITIAL_PROJECTS,
  INITIAL_PLOTS,
  INITIAL_SITE_VISITS,
  INITIAL_BOOKINGS,
  INITIAL_INVESTORS,
  INITIAL_CONSULTATIONS,
  INITIAL_OPPORTUNITIES,
  INITIAL_AUDIT_LOGS,
  INITIAL_NOTIFICATIONS,
  INITIAL_CUSTOM_FIELD_DEFINITIONS,
} from './mockData';

export { TENANTS as DEFAULT_TENANTS, ROLES as SYSTEM_ROLES } from './mockData';
