import {
  Tenant,
  User,
  Role,
  Lead,
  Customer,
  Deal,
  CallRecord,
  Followup,
  PropertyProject,
  Plot,
  SiteVisit,
  Booking,
  Investor,
  Consultation,
  InvestmentOpportunity,
  AuditLog,
  NotificationItem,
  CustomFieldDefinition,
} from '../types';
import { FEATURES } from '../constants/features';
import { PERMISSIONS } from '../constants/permissions';

export const TENANTS: Record<string, Tenant> = {
  ghl: {
    id: 't-ghl-01',
    name: 'GHL India Ventures',
    slug: 'ghl',
    brandColor: '#ef4444',
    logo: '/og-image -GHL Ventures.png',
    tagline: 'Institutional Wealth & Real Estate Investment Advisory',
    enabledFeatures: [
      FEATURES.LEADS,
      FEATURES.CUSTOMERS,
      FEATURES.DEALS,
      FEATURES.FOLLOWUPS,
      FEATURES.CALLS,
      FEATURES.CALL_RECORDING,
      FEATURES.CALL_TRANSCRIPTION,
      FEATURES.INVESTORS,
      FEATURES.CONSULTATIONS,
      FEATURES.INVESTMENT_OPPORTUNITIES,
      FEATURES.REPORTS,
      FEATURES.USERS,
      FEATURES.ROLES,
      FEATURES.COMPANY_SETTINGS,
      FEATURES.AUDIT_LOGS,
      FEATURES.CHAT,
    ],
    timezone: 'Asia/Kolkata (IST)',
    currency: '₹ INR',
    businessHours: '09:30 AM - 07:00 PM IST',
    status: 'Active',
  },
  jamin: {
    id: 't-jamin-02',
    name: 'Jamin Bazaar',
    slug: 'jamin',
    brandColor: '#e10600',
    logo: '/jamin-logo.png',
    tagline: 'Premium Plotted Enclaves & Farmland Communities',
    enabledFeatures: [
      FEATURES.LEADS,
      FEATURES.CUSTOMERS,
      FEATURES.DEALS,
      FEATURES.FOLLOWUPS,
      FEATURES.CALLS,
      FEATURES.CALL_RECORDING,
      FEATURES.CALL_TRANSCRIPTION,
      FEATURES.PROPERTIES,
      FEATURES.SITE_VISITS,
      FEATURES.BOOKINGS,
      FEATURES.REPORTS,
      FEATURES.USERS,
      FEATURES.ROLES,
      FEATURES.COMPANY_SETTINGS,
      FEATURES.AUDIT_LOGS,
      FEATURES.CHAT,
    ],
    timezone: 'Asia/Kolkata (IST)',
    currency: '₹ INR',
    businessHours: '09:00 AM - 06:30 PM IST',
    status: 'Active',
  },
};

export const ROLES: Record<string, Role> = {
  super_admin: {
    id: 'role-super',
    name: 'Super Admin',
    code: 'super_admin',
    permissions: Object.values(PERMISSIONS),
  },
  company_admin: {
    id: 'role-cadmin',
    name: 'Company Admin',
    code: 'company_admin',
    permissions: [
      PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_UPDATE, PERMISSIONS.LEADS_DELETE, PERMISSIONS.LEADS_ASSIGN, PERMISSIONS.LEADS_EXPORT, PERMISSIONS.LEADS_IMPORT, PERMISSIONS.LEADS_CONVERT,
      PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_UPDATE, PERMISSIONS.CUSTOMERS_DELETE,
      PERMISSIONS.DEALS_VIEW, PERMISSIONS.DEALS_CREATE, PERMISSIONS.DEALS_UPDATE, PERMISSIONS.DEALS_DELETE,
      PERMISSIONS.CALLS_MAKE, PERMISSIONS.CALLS_RECEIVE, PERMISSIONS.CALLS_VIEW, PERMISSIONS.CALLS_RECORDINGS_PLAY,
      PERMISSIONS.FOLLOWUPS_VIEW, PERMISSIONS.FOLLOWUPS_CREATE, PERMISSIONS.FOLLOWUPS_UPDATE,
      PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.PROPERTIES_UPDATE, PERMISSIONS.SITE_VISITS_VIEW, PERMISSIONS.SITE_VISITS_CREATE, PERMISSIONS.BOOKINGS_VIEW, PERMISSIONS.BOOKINGS_CREATE,
      PERMISSIONS.INVESTORS_VIEW, PERMISSIONS.INVESTORS_CREATE, PERMISSIONS.CONSULTATIONS_VIEW, PERMISSIONS.CONSULTATIONS_CREATE, PERMISSIONS.OPPORTUNITIES_VIEW, PERMISSIONS.OPPORTUNITIES_CREATE,
      PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
      PERMISSIONS.USERS_VIEW, PERMISSIONS.USERS_MANAGE, PERMISSIONS.ROLES_VIEW, PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_UPDATE, PERMISSIONS.AUDIT_VIEW,
      PERMISSIONS.CHAT_VIEW, PERMISSIONS.CHAT_SEND,
    ],
  },
  sales_manager: {
    id: 'role-mgr',
    name: 'Sales Manager',
    code: 'sales_manager',
    permissions: [
      PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_UPDATE, PERMISSIONS.LEADS_ASSIGN, PERMISSIONS.LEADS_EXPORT, PERMISSIONS.LEADS_CONVERT,
      PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_UPDATE,
      PERMISSIONS.DEALS_VIEW, PERMISSIONS.DEALS_CREATE, PERMISSIONS.DEALS_UPDATE,
      PERMISSIONS.CALLS_MAKE, PERMISSIONS.CALLS_RECEIVE, PERMISSIONS.CALLS_VIEW, PERMISSIONS.CALLS_RECORDINGS_PLAY,
      PERMISSIONS.FOLLOWUPS_VIEW, PERMISSIONS.FOLLOWUPS_CREATE, PERMISSIONS.FOLLOWUPS_UPDATE,
      PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.PROPERTIES_UPDATE, PERMISSIONS.SITE_VISITS_VIEW, PERMISSIONS.SITE_VISITS_CREATE, PERMISSIONS.BOOKINGS_VIEW, PERMISSIONS.BOOKINGS_CREATE,
      PERMISSIONS.INVESTORS_VIEW, PERMISSIONS.INVESTORS_CREATE, PERMISSIONS.CONSULTATIONS_VIEW, PERMISSIONS.CONSULTATIONS_CREATE, PERMISSIONS.OPPORTUNITIES_VIEW, PERMISSIONS.OPPORTUNITIES_CREATE,
      PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
      PERMISSIONS.USERS_VIEW,
      PERMISSIONS.CHAT_VIEW, PERMISSIONS.CHAT_SEND,
    ],
  },
  sales_executive: {
    id: 'role-exec',
    name: 'Sales Executive',
    code: 'sales_executive',
    permissions: [
      PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_UPDATE, PERMISSIONS.LEADS_CONVERT,
      PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_UPDATE,
      PERMISSIONS.DEALS_VIEW, PERMISSIONS.DEALS_CREATE, PERMISSIONS.DEALS_UPDATE,
      PERMISSIONS.CALLS_MAKE, PERMISSIONS.CALLS_RECEIVE, PERMISSIONS.CALLS_VIEW,
      PERMISSIONS.FOLLOWUPS_VIEW, PERMISSIONS.FOLLOWUPS_CREATE, PERMISSIONS.FOLLOWUPS_UPDATE,
      PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.SITE_VISITS_VIEW, PERMISSIONS.SITE_VISITS_CREATE, PERMISSIONS.BOOKINGS_VIEW, PERMISSIONS.BOOKINGS_CREATE,
      PERMISSIONS.INVESTORS_VIEW, PERMISSIONS.INVESTORS_CREATE, PERMISSIONS.CONSULTATIONS_VIEW, PERMISSIONS.CONSULTATIONS_CREATE, PERMISSIONS.OPPORTUNITIES_VIEW, PERMISSIONS.OPPORTUNITIES_CREATE,
      PERMISSIONS.REPORTS_VIEW,
      PERMISSIONS.CHAT_VIEW, PERMISSIONS.CHAT_SEND,
    ],
  },
  irm: {
    id: 'role-irm',
    name: 'IRM',
    code: 'irm',
    permissions: [
      PERMISSIONS.INVESTORS_VIEW,
      PERMISSIONS.INVESTORS_EDIT,
      PERMISSIONS.INVESTORS_CREATE,
      PERMISSIONS.CONSULTATIONS_VIEW,
      PERMISSIONS.CONSULTATIONS_EDIT,
      PERMISSIONS.CONSULTATIONS_CREATE,
      PERMISSIONS.OPPORTUNITIES_VIEW,
      PERMISSIONS.OPPORTUNITIES_EDIT,
      PERMISSIONS.OPPORTUNITIES_CREATE,
      PERMISSIONS.CALL_CENTER,
      PERMISSIONS.CALL_HISTORY,
      PERMISSIONS.REPORTS_VIEW,
      PERMISSIONS.NOTIFICATIONS_VIEW,
      PERMISSIONS.CHAT,
      PERMISSIONS.SMARTY_AI,
      PERMISSIONS.CALL_SETTINGS,
      PERMISSIONS.PROFILE,
    ],
  },
};

export const USERS: User[] = [
  {
    id: 'usr-super-01',
    name: 'Alex Rivera (Super Admin)',
    email: 'alex@nexusplatform.io',
    phone: '+91 98800 11000',
    role: ROLES.super_admin,
    status: 'Active',
    lastLogin: 'Today, 02:15 PM',
  },
  {
    id: 'usr-ghl-admin',
    name: 'Vikram Malhotra',
    email: 'vikram@ghlindiatrust.com',
    phone: '+91 98450 22334',
    role: ROLES.company_admin,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Today, 01:45 PM',
  },
  {
    id: 'usr-ghl-exec',
    name: 'Ananya Iyer',
    email: 'ananya@ghlindiatrust.com',
    phone: '+91 97420 55667',
    role: ROLES.sales_executive,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Today, 11:30 AM',
  },
  {
    id: 'usr-ghl-irm',
    name: 'Rohan Varma',
    email: 'rohan.varma@ghlindiatrust.com',
    phone: '+91 98110 77889',
    role: ROLES.irm,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Today, 10:00 AM',
    designation: 'Investor Relationship Manager',
  },
  {
    id: 'usr-ghl-exec-02',
    name: 'Priya Sharma',
    email: 'priya@ghlindiatrust.com',
    phone: '+91 98450 66778',
    role: ROLES.sales_executive,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Today, 09:45 AM',
  },
  {
    id: 'usr-ghl-exec-03',
    name: 'Rahul Verma',
    email: 'rahul@ghlindiatrust.com',
    phone: '+91 98450 77889',
    role: ROLES.sales_executive,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Today, 09:15 AM',
  },
  {
    id: 'usr-ghl-irm-02',
    name: 'Meera Nair',
    email: 'meera@ghlindiatrust.com',
    phone: '+91 98450 88990',
    role: ROLES.irm,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Today, 10:30 AM',
    designation: 'Senior IRM Partner',
  },
  {
    id: 'usr-ghl-irm-03',
    name: 'Sameer Joshi',
    email: 'sameer@ghlindiatrust.com',
    phone: '+91 98450 99001',
    role: ROLES.irm,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Yesterday, 04:00 PM',
    designation: 'Institutional IRM Partner',
  },
  {
    id: 'usr-jamin-admin',
    name: 'Kavita Rao',
    email: 'kavita@jaminbazaar.com',
    phone: '+91 98860 33445',
    role: ROLES.company_admin,
    companyId: 't-jamin-02',
    companySlug: 'jamin',
    companyName: 'Jamin Bazaar',
    status: 'Active',
    lastLogin: 'Today, 02:00 PM',
  },
  {
    id: 'usr-jamin-exec',
    name: 'Pooja Hegde',
    email: 'pooja@jaminbazaar.com',
    phone: '+91 99160 44889',
    role: ROLES.sales_executive,
    companyId: 't-jamin-02',
    companySlug: 'jamin',
    companyName: 'Jamin Bazaar',
    status: 'Active',
    lastLogin: 'Today, 10:15 AM',
  },
];

export const INITIAL_LEADS: Lead[] = [
  // GHL Leads
  {
    id: 'lead-ghl-01',
    companyId: 't-ghl-01',
    name: 'Dr. Rajesh Nambiar',
    phone: '+91 98451 12233',
    email: 'dr.nambiar@cardiohealth.in',
    location: 'Indiranagar, Bengaluru',
    source: 'Referral - HNW Club',
    status: 'Qualified',
    priority: 'Urgent',
    assignedAgentId: 'usr-ghl-exec',
    assignedAgentName: 'Ananya Iyer',
    nextFollowupDate: 'Today, 04:30 PM',
    createdAt: '2026-03-08',
    notes: 'Interested in commercial Grade-A pre-leased office asset. Liquid capital ready.',
    customFields: {
      investmentCapacity: '₹3 Cr - ₹5 Cr',
      preferredAssetClass: 'Commercial REIT / Pre-Leased',
      horizon: '5-7 Years',
    },
  },
  {
    id: 'lead-ghl-02',
    companyId: 't-ghl-01',
    name: 'Sunita & Arvind Mehta',
    phone: '+91 99882 33445',
    email: 'arvind.mehta@techscale.io',
    location: 'Koramangala, Bengaluru',
    source: 'LinkedIn Executive Campaign',
    status: 'Proposal',
    priority: 'High',
    assignedAgentId: 'usr-ghl-exec',
    assignedAgentName: 'Ananya Iyer',
    nextFollowupDate: 'Tomorrow, 11:00 AM',
    createdAt: '2026-03-07',
    notes: 'NRI returning from Singapore. Evaluating fractional warehouse logistics yield.',
    customFields: {
      investmentCapacity: '₹1.5 Cr - ₹3 Cr',
      preferredAssetClass: 'Industrial Logistics Park',
      horizon: '3-5 Years',
    },
  },
  {
    id: 'lead-ghl-03',
    companyId: 't-ghl-01',
    name: 'Karthik Somayaji',
    phone: '+91 94480 77889',
    email: 'karthik.s@somayajient.com',
    location: 'Jayanagar, Bengaluru',
    source: 'Website Inbound',
    status: 'New',
    priority: 'Medium',
    assignedAgentId: 'usr-ghl-admin',
    assignedAgentName: 'Vikram Malhotra',
    nextFollowupDate: 'Tomorrow, 02:00 PM',
    createdAt: '2026-03-09',
    notes: 'Inquired through web form regarding tax-optimized commercial yield funds.',
    customFields: {
      investmentCapacity: '₹75L - ₹1.5 Cr',
      preferredAssetClass: 'Commercial Yield Funds',
      horizon: '5 Years',
    },
  },

  // Jamin Leads
  {
    id: 'lead-jam-01',
    companyId: 't-jamin-02',
    name: 'Manjunath Swamy',
    phone: '+91 98801 44556',
    email: 'manjunath.swamy@infrareach.com',
    location: 'Whitefield, Bengaluru',
    source: 'Facebook Ad - Greenfield Meadows',
    status: 'Contacted',
    priority: 'High',
    assignedAgentId: 'usr-jamin-exec',
    assignedAgentName: 'Pooja Hegde',
    nextFollowupDate: 'Today, 05:00 PM',
    createdAt: '2026-03-09',
    notes: 'Looking for 2400 sqft corner plot facing East for villa construction in next 2 years.',
    customFields: {
      budgetRange: '₹65L - ₹90L',
      preferredLocation: 'Devanahalli North',
      readyToRegister: 'Within 30 Days',
    },
  },
  {
    id: 'lead-jam-02',
    companyId: 't-jamin-02',
    name: 'Deepak & Sneha Kulkarni',
    phone: '+91 97312 88990',
    email: 'deepak.kulkarni@wipro.com',
    location: 'Electronic City, Bengaluru',
    source: 'Google Search - Villa Plots',
    status: 'Qualified',
    priority: 'Urgent',
    assignedAgentId: 'usr-jamin-exec',
    assignedAgentName: 'Pooja Hegde',
    nextFollowupDate: 'Saturday, 10:30 AM',
    createdAt: '2026-03-06',
    notes: 'Wants to schedule weekend site visit for Greenfield Meadows Plots #14 and #15.',
    customFields: {
      budgetRange: '₹45L - ₹65L',
      preferredLocation: 'Sarjapur East',
      readyToRegister: 'Immediate',
    },
  },
  {
    id: 'lead-jam-03',
    companyId: 't-jamin-02',
    name: 'Brigadier H.S. Rathore (Retd)',
    phone: '+91 94140 11223',
    email: 'hsrathore@defencecolony.org',
    location: 'Hebbal, Bengaluru',
    source: 'Walk-in Site Office',
    status: 'Negotiation',
    priority: 'High',
    assignedAgentId: 'usr-jamin-admin',
    assignedAgentName: 'Kavita Rao',
    nextFollowupDate: 'Today, 03:00 PM',
    createdAt: '2026-03-04',
    notes: 'Selected Plot #08. Discussing 5% senior citizen concession and payment schedule.',
    customFields: {
      budgetRange: '₹80L - ₹1.1 Cr',
      preferredLocation: 'Airport Corridor North',
      readyToRegister: 'Within 15 Days',
    },
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  // GHL Customer
  {
    id: 'cust-ghl-01',
    companyId: 't-ghl-01',
    name: 'Venkatraman Narayanan',
    phone: '+91 98450 99887',
    email: 'v.narayanan@apexholdings.sg',
    status: 'VIP',
    assignedAgentId: 'usr-ghl-admin',
    assignedAgentName: 'Vikram Malhotra',
    location: 'Sadashivanagar, Bengaluru',
    lastContacted: 'Yesterday, 04:15 PM',
    openDealsCount: 1,
    totalValue: 45000000,
    createdAt: '2026-01-15',
    notes: 'Chairman of Singapore-based family office. Invested in Phase 1 warehousing asset.',
    customFields: {
      investorType: 'Family Office / Institutional',
      totalAUMCommitted: '₹4.5 Cr',
      relationshipManager: 'Vikram Malhotra',
    },
  },
  // Jamin Customer
  {
    id: 'cust-jam-01',
    companyId: 't-jamin-02',
    name: 'Siddharth Rao',
    phone: '+91 99001 77665',
    email: 'siddharth.rao@accenture.com',
    status: 'Active',
    assignedAgentId: 'usr-jamin-exec',
    assignedAgentName: 'Pooja Hegde',
    location: 'HSR Layout, Bengaluru',
    lastContacted: '2 days ago',
    openDealsCount: 1,
    totalValue: 7200000,
    createdAt: '2026-02-10',
    notes: 'Completed site visit on Feb 22. Placed booking token for Greenfield Meadows Plot #22.',
    customFields: {
      preferredPaymentBank: 'HDFC Home Loans',
      advocateAssigned: 'M.K. Associates',
    },
  },
];

export const INITIAL_DEALS: Deal[] = [
  // GHL Deals
  {
    id: 'deal-ghl-01',
    companyId: 't-ghl-01',
    title: 'Pre-Leased IT Park Suite (Floor 4)',
    customerId: 'cust-ghl-01',
    customerName: 'Venkatraman Narayanan',
    stage: 'investment_opportunity',
    value: 45000000,
    expectedCloseDate: '2026-03-25',
    assignedAgentId: 'usr-ghl-admin',
    assignedAgentName: 'Vikram Malhotra',
    notes: 'Term sheet shared. Waiting for legal review on tenant lock-in clause (9 years).',
    createdAt: '2026-02-15',
  },
  {
    id: 'deal-ghl-02',
    companyId: 't-ghl-01',
    title: 'Commercial Logistics Fractional Tranche B',
    customerId: 'lead-ghl-01',
    customerName: 'Dr. Rajesh Nambiar',
    stage: 'qualified_investor',
    value: 35000000,
    expectedCloseDate: '2026-04-10',
    assignedAgentId: 'usr-ghl-exec',
    assignedAgentName: 'Ananya Iyer',
    notes: 'KYC verified. Advisory deck presented. Follow up consultation scheduled.',
    createdAt: '2026-03-01',
  },
  // Jamin Deals
  {
    id: 'deal-jam-01',
    companyId: 't-jamin-02',
    title: 'Plot #22 (2400 sqft) - Greenfield Meadows',
    customerId: 'cust-jam-01',
    customerName: 'Siddharth Rao',
    stage: 'booking',
    value: 7200000,
    expectedCloseDate: '2026-03-18',
    assignedAgentId: 'usr-jamin-exec',
    assignedAgentName: 'Pooja Hegde',
    notes: '₹5L token received. Sale agreement draft shared with advocate for approval.',
    createdAt: '2026-02-22',
  },
  {
    id: 'deal-jam-02',
    companyId: 't-jamin-02',
    title: 'Plot #08 (1800 sqft) - North Corner',
    customerId: 'lead-jam-03',
    customerName: 'Brigadier H.S. Rathore (Retd)',
    stage: 'plot_selected',
    value: 5760000,
    expectedCloseDate: '2026-03-22',
    assignedAgentId: 'usr-jamin-admin',
    assignedAgentName: 'Kavita Rao',
    notes: 'Plot put on 7-day hold. Finalizing token date and club house membership waiver.',
    createdAt: '2026-03-04',
  },
];

export const INITIAL_CALLS: CallRecord[] = [
  {
    id: 'call-01',
    companyId: 't-ghl-01',
    contactName: 'Dr. Rajesh Nambiar',
    contactPhone: '+91 98451 12233',
    direction: 'outbound',
    duration: 384, // 6m 24s
    agentId: 'usr-ghl-exec',
    agentName: 'Ananya Iyer',
    disposition: 'Interested',
    timestamp: 'Today, 11:20 AM',
    recordingUrl: 'https://cdn.nexusplatform.io/recordings/call-01.mp3',
    transcription: 'Agent explained commercial cap rate (8.8% gross yield) and 3-year rent escalation. Investor confirmed interest in scheduling 1-on-1 wealth consultation.',
    notes: 'Very receptive. Sent advisory memorandum on WhatsApp.',
  },
  {
    id: 'call-02',
    companyId: 't-jamin-02',
    contactName: 'Deepak Kulkarni',
    contactPhone: '+91 97312 88990',
    direction: 'inbound',
    duration: 215, // 3m 35s
    agentId: 'usr-jamin-exec',
    agentName: 'Pooja Hegde',
    disposition: 'Follow-up Required',
    timestamp: 'Today, 10:45 AM',
    recordingUrl: 'https://cdn.nexusplatform.io/recordings/call-02.mp3',
    transcription: 'Customer called inquiring about BDA/BIAAPA approvals for Greenfield Meadows. Agent confirmed clear titles and RERA registration PRM/KA/RERA/1250/303/PR/240101.',
    notes: 'Wants weekend site visit confirmation by Friday evening.',
  },
  {
    id: 'call-03',
    companyId: 't-jamin-02',
    contactName: 'Siddharth Rao',
    contactPhone: '+91 99001 77665',
    direction: 'outbound',
    duration: 142,
    agentId: 'usr-jamin-exec',
    agentName: 'Pooja Hegde',
    disposition: 'Converted',
    timestamp: 'Yesterday, 04:30 PM',
    notes: 'Token confirmation call. Siddharth transferred ₹5,00,000 via RTGS.',
  },
];

export const INITIAL_FOLLOWUPS: Followup[] = [
  {
    id: 'flw-01',
    companyId: 't-ghl-01',
    contactId: 'lead-ghl-01',
    contactName: 'Dr. Rajesh Nambiar',
    contactPhone: '+91 98451 12233',
    contactType: 'lead',
    scheduledAt: 'Today, 04:30 PM',
    priority: 'High',
    status: 'Pending',
    notes: 'Call to confirm private wealth advisor slot for Thursday morning.',
    assignedAgentId: 'usr-ghl-exec',
    assignedAgentName: 'Ananya Iyer',
  },
  {
    id: 'flw-02',
    companyId: 't-jamin-02',
    contactId: 'lead-jam-01',
    contactName: 'Manjunath Swamy',
    contactPhone: '+91 98801 44556',
    contactType: 'lead',
    scheduledAt: 'Today, 05:00 PM',
    priority: 'High',
    status: 'Pending',
    notes: 'Send video walkthrough of Phase 2 clubhouse and park-facing plots.',
    assignedAgentId: 'usr-jamin-exec',
    assignedAgentName: 'Pooja Hegde',
  },
  {
    id: 'flw-03',
    companyId: 't-jamin-02',
    contactId: 'lead-jam-03',
    contactName: 'Brigadier H.S. Rathore (Retd)',
    contactPhone: '+91 94140 11223',
    contactType: 'lead',
    scheduledAt: 'Yesterday, 06:00 PM',
    priority: 'High',
    status: 'Pending', // Overdue!
    notes: 'Deliver printed sanction layout map to residence in Hebbal.',
    assignedAgentId: 'usr-jamin-admin',
    assignedAgentName: 'Kavita Rao',
  },
];

// Jamin Specific Data
export const INITIAL_PROJECTS: PropertyProject[] = [
  {
    id: 'proj-01',
    name: 'Greenfield Meadows Phase 2',
    location: 'North Bengaluru (Near International Airport)',
    status: 'Active',
    totalPlots: 48,
    availablePlots: 18,
    holdPlots: 6,
    soldPlots: 24,
    description: 'BIAAPA approved luxury gated villa enclave with 40-foot wide asphalted roads, underground cabling, and organic orchard.',
    priceRange: '₹3,000 - ₹3,400 / sq.ft',
  },
  {
    id: 'proj-02',
    name: 'Valley Crest Country Estates',
    location: 'Sarjapur East Extension',
    status: 'Active',
    totalPlots: 36,
    availablePlots: 12,
    holdPlots: 4,
    soldPlots: 20,
    description: 'Eco-conscious farmland community featuring teak groves, clubhouse, solar streetlights, and 24/7 smart security.',
    priceRange: '₹1,850 - ₹2,200 / sq.ft',
  },
  {
    id: 'proj-03',
    name: 'Emerald Orchid Enclave',
    location: 'Mysore Highway Corridor',
    status: 'Upcoming',
    totalPlots: 60,
    availablePlots: 55,
    holdPlots: 5,
    soldPlots: 0,
    description: 'Premium resort-themed residential layout with private lake access and wellness center.',
    priceRange: '₹2,100 / sq.ft (Pre-Launch)',
  },
];

export const INITIAL_PLOTS: Plot[] = [
  { id: 'plot-01', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #01', sizeSqft: 2400, pricePerSqft: 3200, totalPrice: 7680000, status: 'Sold', dimension: '40 x 60', facing: 'East' },
  { id: 'plot-02', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #02', sizeSqft: 2400, pricePerSqft: 3200, totalPrice: 7680000, status: 'Sold', dimension: '40 x 60', facing: 'East' },
  { id: 'plot-03', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #03', sizeSqft: 1800, pricePerSqft: 3100, totalPrice: 5580000, status: 'Available', dimension: '30 x 60', facing: 'North' },
  { id: 'plot-04', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #04', sizeSqft: 1800, pricePerSqft: 3100, totalPrice: 5580000, status: 'Available', dimension: '30 x 60', facing: 'North' },
  { id: 'plot-05', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #05', sizeSqft: 1500, pricePerSqft: 3000, totalPrice: 4500000, status: 'Available', dimension: '30 x 50', facing: 'West' },
  { id: 'plot-06', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #06', sizeSqft: 1500, pricePerSqft: 3000, totalPrice: 4500000, status: 'Available', dimension: '30 x 50', facing: 'West' },
  { id: 'plot-07', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #07', sizeSqft: 1500, pricePerSqft: 3000, totalPrice: 4500000, status: 'Hold', dimension: '30 x 50', facing: 'East', holdByCustomer: 'Sunil Rao', holdByAgent: 'Pooja Hegde', holdExpiry: '2026-03-14' },
  { id: 'plot-08', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #08', sizeSqft: 1800, pricePerSqft: 3200, totalPrice: 5760000, status: 'Hold', dimension: '30 x 60', facing: 'North Corner', holdByCustomer: 'Brigadier H.S. Rathore', holdByAgent: 'Kavita Rao', holdExpiry: '2026-03-12' },
  { id: 'plot-09', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #09', sizeSqft: 2400, pricePerSqft: 3300, totalPrice: 7920000, status: 'Available', dimension: '40 x 60', facing: 'East Park Facing' },
  { id: 'plot-10', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #10', sizeSqft: 2400, pricePerSqft: 3300, totalPrice: 7920000, status: 'Available', dimension: '40 x 60', facing: 'East Park Facing' },
  { id: 'plot-11', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #11', sizeSqft: 1200, pricePerSqft: 3000, totalPrice: 3600000, status: 'Sold', dimension: '30 x 40', facing: 'South' },
  { id: 'plot-12', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #12', sizeSqft: 1200, pricePerSqft: 3000, totalPrice: 3600000, status: 'Sold', dimension: '30 x 40', facing: 'South' },
  { id: 'plot-13', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #13', sizeSqft: 1500, pricePerSqft: 3050, totalPrice: 4575000, status: 'Available', dimension: '30 x 50', facing: 'East' },
  { id: 'plot-14', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #14', sizeSqft: 1500, pricePerSqft: 3050, totalPrice: 4575000, status: 'Available', dimension: '30 x 50', facing: 'East' },
  { id: 'plot-15', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #15', sizeSqft: 1800, pricePerSqft: 3100, totalPrice: 5580000, status: 'Available', dimension: '30 x 60', facing: 'North' },
  { id: 'plot-16', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #16', sizeSqft: 1800, pricePerSqft: 3100, totalPrice: 5580000, status: 'Hold', dimension: '30 x 60', facing: 'North', holdByCustomer: 'Girish Kumar', holdByAgent: 'Suresh Babu', holdExpiry: '2026-03-15' },
  { id: 'plot-22', projectId: 'proj-01', projectName: 'Greenfield Meadows Phase 2', plotNumber: 'Plot #22', sizeSqft: 2400, pricePerSqft: 3000, totalPrice: 7200000, status: 'Sold', dimension: '40 x 60', facing: 'East', holdByCustomer: 'Siddharth Rao' },
];

export const INITIAL_SITE_VISITS: SiteVisit[] = [
  {
    id: 'sv-01',
    companyId: 't-jamin-02',
    customerId: 'lead-jam-02',
    customerName: 'Deepak & Sneha Kulkarni',
    customerPhone: '+91 97312 88990',
    projectId: 'proj-01',
    projectName: 'Greenfield Meadows Phase 2',
    plotNumber: 'Plots #14 & #15',
    scheduledAt: 'This Saturday, 10:30 AM',
    assignedAgentId: 'usr-jamin-exec',
    assignedAgentName: 'Pooja Hegde',
    status: 'Scheduled',
    outcomeNotes: 'Customer requested cab pickup from Electronic City junction.',
  },
  {
    id: 'sv-02',
    companyId: 't-jamin-02',
    customerId: 'cust-jam-01',
    customerName: 'Siddharth Rao',
    customerPhone: '+91 99001 77665',
    projectId: 'proj-01',
    projectName: 'Greenfield Meadows Phase 2',
    plotNumber: 'Plot #22',
    scheduledAt: '2026-02-22, 11:00 AM',
    assignedAgentId: 'usr-jamin-exec',
    assignedAgentName: 'Pooja Hegde',
    status: 'Completed',
    outcomeNotes: 'Client thoroughly impressed by underground electrical lines and 40-foot main boulevard. Selected Plot #22 on the spot.',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bkg-01',
    companyId: 't-jamin-02',
    customerId: 'cust-jam-01',
    customerName: 'Siddharth Rao',
    customerPhone: '+91 99001 77665',
    projectId: 'proj-01',
    projectName: 'Greenfield Meadows Phase 2',
    plotId: 'plot-22',
    plotNumber: 'Plot #22',
    bookingDate: '2026-02-23',
    bookingAmount: 500000,
    totalAmount: 7200000,
    status: 'Confirmed',
    agentId: 'usr-jamin-exec',
    agentName: 'Pooja Hegde',
    paymentTerms: 'Token ₹5L paid via RTGS. 20% on agreement signing (March 18), 80% upon registration via HDFC loan.',
  },
];

// GHL Specific Data
export const INITIAL_INVESTORS: Investor[] = [
  {
    id: 'inv-01',
    companyId: 't-ghl-01',
    name: 'Venkatraman Narayanan',
    phone: '+91 98450 99887',
    email: 'v.narayanan@apexholdings.sg',
    status: 'Active Investor',
    investmentCapacity: '₹5 Cr - ₹10 Cr',
    preferredAssetClass: 'Commercial Grade-A / Pre-Leased',
    assignedAgentId: 'usr-ghl-admin',
    assignedAgentName: 'Vikram Malhotra',
    referralSource: 'Global Indian Wealth Network',
    createdAt: '2026-01-10',
    committedAUM: '₹8 Cr',
    notes: 'Focus on Bengaluru Outer Ring Road and Whitefield commercial IT assets.',
  },
  {
    id: 'inv-02',
    companyId: 't-ghl-01',
    name: 'Dr. Rajesh Nambiar',
    phone: '+91 98451 12233',
    email: 'dr.nambiar@cardiohealth.in',
    status: 'Lead',
    investmentCapacity: '₹3 Cr - ₹5 Cr',
    preferredAssetClass: 'Pre-Leased Commercial & Warehousing',
    assignedAgentId: 'usr-ghl-exec',
    assignedAgentName: 'Ananya Iyer',
    referralSource: 'HNW Doctors Syndicate',
    createdAt: '2026-03-08',
    committedAUM: '₹4 Cr',
    notes: 'Evaluating 9-year pre-leased banking branch floor in Koramangala.',
  },
  {
    id: 'inv-03',
    companyId: 't-ghl-01',
    name: 'Siddharth Singhania',
    phone: '+91 98200 44556',
    email: 'siddharth@singhaniafamilyoffice.com',
    status: 'HNW Investor',
    investmentCapacity: '₹10 Cr - ₹25 Cr',
    preferredAssetClass: 'Grade-A IT Parks & Logistics',
    assignedAgentId: 'usr-ghl-irm',
    assignedAgentName: 'Rohan Varma',
    referralSource: 'Family Office Conclave',
    createdAt: '2026-03-14',
    committedAUM: '₹15 Cr',
    notes: 'Looking for core yielding commercial assets with minimum 8.5% cap rate.',
  },
  {
    id: 'inv-04',
    companyId: 't-ghl-01',
    name: 'Meera Chidambaram',
    phone: '+91 98401 77665',
    email: 'meera.c@chennaicapital.com',
    status: 'Active Investor',
    investmentCapacity: '₹5 Cr - ₹10 Cr',
    preferredAssetClass: 'Pre-Leased Commercial & Warehousing',
    assignedAgentId: 'usr-ghl-irm',
    assignedAgentName: 'Rohan Varma',
    referralSource: 'Direct Inbound',
    createdAt: '2026-03-16',
    committedAUM: '₹6.5 Cr',
    notes: 'Interested in Bengaluru-Chennai corridor logistics & tech parks.',
  },
  {
    id: 'inv-05',
    companyId: 't-ghl-01',
    name: 'Aditya Birla Singhal',
    phone: '+91 98199 33221',
    email: 'aditya.singhal@singhalholdings.in',
    status: 'Active Investor',
    investmentCapacity: '₹15 Cr - ₹30 Cr',
    preferredAssetClass: 'Data Centers & Industrial REITs',
    assignedAgentId: 'usr-ghl-irm',
    assignedAgentName: 'Rohan Varma',
    referralSource: 'Private Wealth Advisory',
    createdAt: '2026-03-18',
    committedAUM: '₹12 Cr',
    notes: 'Evaluating multi-tenant data center park in Whitefield.',
  },
  {
    id: 'inv-06',
    companyId: 't-ghl-01',
    name: 'Sunita Kashyap',
    phone: '+91 98300 88776',
    email: 'sunita.kashyap@kashyappharma.com',
    status: 'Lead',
    investmentCapacity: '₹2 Cr - ₹5 Cr',
    preferredAssetClass: 'Commercial Grade-A',
    assignedAgentId: 'usr-ghl-irm',
    assignedAgentName: 'Rohan Varma',
    referralSource: 'Executive Referral',
    createdAt: '2026-03-19',
    committedAUM: '₹3.5 Cr',
    notes: 'First-time fractional commercial investor exploring pre-leased retail.',
  },
];

export const INITIAL_CONSULTATIONS: Consultation[] = [
  {
    id: 'cns-01',
    companyId: 't-ghl-01',
    investorId: 'inv-01',
    investorName: 'Venkatraman Narayanan',
    investorPhone: '+91 98450 99887',
    scheduledAt: 'Thursday, 03:00 PM',
    consultantId: 'usr-ghl-admin',
    consultantName: 'Vikram Malhotra',
    status: 'Scheduled',
    agenda: 'Review lease deed covenants and tax pass-through structure for Pre-Leased IT Park Suite.',
    outcomeNotes: 'Financial models and tenant credit rating sheets prepared.',
  },
  {
    id: 'cns-02',
    companyId: 't-ghl-01',
    investorId: 'inv-02',
    investorName: 'Dr. Rajesh Nambiar',
    investorPhone: '+91 98451 12233',
    scheduledAt: '2026-03-09, 04:00 PM',
    consultantId: 'usr-ghl-exec',
    consultantName: 'Ananya Iyer',
    status: 'Completed',
    agenda: 'Introductory advisory on fractional commercial real estate yields vs residential rental yields.',
    outcomeNotes: 'Client expressed clear interest in Grade-A commercial asset. Next step: Term sheet.',
  },
  {
    id: 'cns-03',
    companyId: 't-ghl-01',
    investorId: 'inv-03',
    investorName: 'Siddharth Singhania',
    investorPhone: '+91 98200 44556',
    scheduledAt: 'Tomorrow, 11:00 AM',
    consultantId: 'usr-ghl-irm',
    consultantName: 'Rohan Varma',
    status: 'Scheduled',
    agenda: 'Whitefield Grade-A IT Park tranche allocation and yields discussion.',
    outcomeNotes: 'Term sheet shared; awaiting confirmation on ₹15 Cr ticket.',
  },
  {
    id: 'cns-04',
    companyId: 't-ghl-01',
    investorId: 'inv-04',
    investorName: 'Meera Chidambaram',
    investorPhone: '+91 98401 77665',
    scheduledAt: 'Friday, 02:30 PM',
    consultantId: 'usr-ghl-irm',
    consultantName: 'Rohan Varma',
    status: 'Scheduled',
    agenda: 'Review lease deed covenants and tax structure for Pre-Leased Logistics Hub.',
    outcomeNotes: 'Preparing comparison matrix for 9% gross yield.',
  },
];

export const INITIAL_OPPORTUNITIES: InvestmentOpportunity[] = [
  {
    id: 'opp-01',
    companyId: 't-ghl-01',
    title: 'ORR Tech Park Pre-Leased Level 4 (9.1% Gross Yield)',
    investorId: 'inv-01',
    investorName: 'Venkatraman Narayanan',
    stage: 'Committed',
    targetAmount: 45000000,
    committedAmount: 45000000,
    assignedAgentId: 'usr-ghl-admin',
    assignedAgentName: 'Vikram Malhotra',
    expectedCloseDate: '2026-03-25',
    notes: 'Escrow account established. Legal diligence completed by Khaitan & Co.',
  },
  {
    id: 'opp-02',
    companyId: 't-ghl-01',
    title: 'Hosakote Mega Logistics Hub Tranche B',
    investorId: 'inv-02',
    investorName: 'Dr. Rajesh Nambiar',
    stage: 'Opportunity',
    targetAmount: 35000000,
    committedAmount: 20000000,
    assignedAgentId: 'usr-ghl-exec',
    assignedAgentName: 'Ananya Iyer',
    expectedCloseDate: '2026-04-15',
    notes: '12-year lease with Fortune 500 ecommerce tenant. Annual escalation 5%.',
  },
  {
    id: 'opp-03',
    companyId: 't-ghl-01',
    title: 'Whitefield Cyber Hub Grade-A Pre-Leased Floor (8.8% Yield)',
    investorId: 'inv-03',
    investorName: 'Siddharth Singhania',
    stage: 'Committed',
    targetAmount: 150000000,
    committedAmount: 150000000,
    assignedAgentId: 'usr-ghl-irm',
    assignedAgentName: 'Rohan Varma',
    expectedCloseDate: '2026-03-30',
    notes: 'MNC banking tenant on 9-year lock-in. Escrow terms agreed.',
  },
  {
    id: 'opp-04',
    companyId: 't-ghl-01',
    title: 'Outer Ring Road Fintech Center Tranche A',
    investorId: 'inv-04',
    investorName: 'Meera Chidambaram',
    stage: 'Opportunity',
    targetAmount: 65000000,
    committedAmount: 65000000,
    assignedAgentId: 'usr-ghl-irm',
    assignedAgentName: 'Rohan Varma',
    expectedCloseDate: '2026-04-10',
    notes: 'Due diligence stage with legal advisors.',
  },
  {
    id: 'opp-05',
    companyId: 't-ghl-01',
    title: 'Electronic City Cloud Data Park Unit 3',
    investorId: 'inv-05',
    investorName: 'Aditya Birla Singhal',
    stage: 'Qualified',
    targetAmount: 120000000,
    committedAmount: 120000000,
    assignedAgentId: 'usr-ghl-irm',
    assignedAgentName: 'Rohan Varma',
    expectedCloseDate: '2026-04-20',
    notes: 'Tier-4 certified hyperscale data facility.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-01',
    timestamp: 'Today, 02:10 PM',
    actorName: 'Pooja Hegde',
    actorEmail: 'pooja@jaminbazaar.com',
    action: 'PLOT_HOLD_CREATED',
    entityType: 'Plot',
    entityId: 'plot-07',
    companyId: 't-jamin-02',
    companyName: 'Jamin Bazaar',
    details: 'Placed Plot #07 on 7-day hold for Sunil Rao.',
  },
  {
    id: 'aud-02',
    timestamp: 'Today, 11:20 AM',
    actorName: 'Ananya Iyer',
    actorEmail: 'ananya@ghlindiatrust.com',
    action: 'CALL_DISPOSITION_LOGGED',
    entityType: 'CallRecord',
    entityId: 'call-01',
    companyId: 't-ghl-01',
    companyName: 'GHL India Ventures',
    details: 'Logged disposition "Interested" for call with Dr. Rajesh Nambiar.',
  },
  {
    id: 'aud-03',
    timestamp: 'Yesterday, 04:35 PM',
    actorName: 'Kavita Rao',
    actorEmail: 'kavita@jaminbazaar.com',
    action: 'BOOKING_CONFIRMED',
    entityType: 'Booking',
    entityId: 'bkg-01',
    companyId: 't-jamin-02',
    companyName: 'Jamin Bazaar',
    details: 'Confirmed Plot #22 booking for Siddharth Rao (Token ₹5,00,000 received).',
  },
  {
    id: 'aud-04',
    timestamp: 'Yesterday, 02:15 PM',
    actorName: 'Alex Rivera',
    actorEmail: 'alex@nexusplatform.io',
    action: 'TENANT_FEATURE_UPDATED',
    entityType: 'Tenant',
    entityId: 't-ghl-01',
    details: 'Super Admin activated feature "call-transcription" for GHL India Ventures.',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  // ── GHL India Ventures Notifications ─────────────────────────────────────
  {
    id: 'notif-01',
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    type: 'call',
    title: 'Incoming Call Record Available',
    message: 'Recording and automated transcript ready for Dr. Rajesh Nambiar (6m 24s).',
    timestamp: '2 hours ago',
    read: false,
    link: '/call-history',
    priority: 'normal',
    targetUserId: 'all',
  },
  {
    id: 'notif-02',
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    type: 'followup',
    title: 'Follow-up Due in 30 Minutes',
    message: 'Follow-up with Dr. Rajesh Nambiar scheduled at 04:30 PM.',
    timestamp: '35 mins ago',
    read: false,
    link: '/followups',
    priority: 'important',
    targetUserId: 'all',
  },
  {
    id: 'notif-03',
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    type: 'lead',
    title: 'New High Priority Lead Assigned',
    message: 'Karthik Somayaji assigned by Vikram Malhotra.',
    timestamp: 'Yesterday',
    read: true,
    link: '/leads',
    priority: 'normal',
    targetUserId: 'all',
  },

  // ── Jamin Bazaar Notifications ───────────────────────────────────────────
  {
    id: 'notif-jam-01',
    companyId: 't-jamin-02',
    companySlug: 'jamin',
    type: 'visit',
    title: 'Site Visit Confirmed - Phase 2',
    message: 'Manjunath Swamy scheduled site visit for Phase 2 Green Valley plots tomorrow at 10:00 AM.',
    timestamp: '1 hour ago',
    read: false,
    link: '/site-visits',
    priority: 'important',
    targetUserId: 'all',
  },
  {
    id: 'notif-jam-02',
    companyId: 't-jamin-02',
    companySlug: 'jamin',
    type: 'booking',
    title: 'Token Advance Received',
    message: 'Token advance of ₹5,00,000 received from Brigadier H.S. Rathore for Villa Plot #42.',
    timestamp: 'Yesterday',
    read: true,
    link: '/bookings',
    priority: 'normal',
    targetUserId: 'all',
  },
];

export const INITIAL_CUSTOM_FIELD_DEFINITIONS: CustomFieldDefinition[] = [
  // GHL India Ventures - Leads
  {
    id: 'cf-ghl-lead-1',
    companyId: 't-ghl-01',
    module: 'leads',
    fieldKey: 'investmentCapacity',
    label: 'Investment Capacity',
    fieldType: 'select',
    required: false,
    options: ['₹50L - ₹1 Cr', '₹75L - ₹1.5 Cr', '₹1 Cr - ₹3 Cr', '₹1.5 Cr - ₹3 Cr', '₹3 Cr - ₹5 Cr', '₹5 Cr+'],
    defaultValue: '₹1 Cr - ₹3 Cr',
    displayOrder: 1,
    active: true,
  },
  {
    id: 'cf-ghl-lead-2',
    companyId: 't-ghl-01',
    module: 'leads',
    fieldKey: 'preferredAssetClass',
    label: 'Preferred Asset Class',
    fieldType: 'select',
    required: false,
    options: ['Commercial Pre-Leased', 'Commercial REIT / Pre-Leased', 'Industrial Logistics Park', 'Commercial Yield Funds'],
    defaultValue: 'Commercial Pre-Leased',
    displayOrder: 2,
    active: true,
  },
  {
    id: 'cf-ghl-lead-3',
    companyId: 't-ghl-01',
    module: 'leads',
    fieldKey: 'horizon',
    label: 'Investment Horizon',
    fieldType: 'text',
    required: false,
    defaultValue: '3-5 Years',
    displayOrder: 3,
    active: true,
  },

  // Jamin Bazaar - Leads
  {
    id: 'cf-jam-lead-1',
    companyId: 't-jamin-02',
    module: 'leads',
    fieldKey: 'budgetRange',
    label: 'Plot Budget Range',
    fieldType: 'select',
    required: false,
    options: ['₹25L - ₹45L', '₹45L - ₹65L', '₹65L - ₹90L', '₹80L - ₹1.1 Cr', '₹90L+'],
    defaultValue: '₹45L - ₹65L',
    displayOrder: 1,
    active: true,
  },
  {
    id: 'cf-jam-lead-2',
    companyId: 't-jamin-02',
    module: 'leads',
    fieldKey: 'preferredLocation',
    label: 'Preferred Micro-Market',
    fieldType: 'select',
    required: false,
    options: ['Devanahalli North', 'Sarjapur East', 'Mysore Highway Corridor', 'Airport Corridor North'],
    defaultValue: 'Devanahalli North',
    displayOrder: 2,
    active: true,
  },
  {
    id: 'cf-jam-lead-3',
    companyId: 't-jamin-02',
    module: 'leads',
    fieldKey: 'readyToRegister',
    label: 'Ready to Register',
    fieldType: 'text',
    required: false,
    defaultValue: 'Within 30 Days',
    displayOrder: 3,
    active: true,
  },

  // GHL India Ventures - Customers
  {
    id: 'cf-ghl-cust-1',
    companyId: 't-ghl-01',
    module: 'customers',
    fieldKey: 'investorType',
    label: 'Investor Type',
    fieldType: 'text',
    required: false,
    defaultValue: 'Family Office / Institutional',
    displayOrder: 1,
    active: true,
  },
  {
    id: 'cf-ghl-cust-2',
    companyId: 't-ghl-01',
    module: 'customers',
    fieldKey: 'totalAUMCommitted',
    label: 'Total AUM Committed',
    fieldType: 'text',
    required: false,
    defaultValue: '₹4.5 Cr',
    displayOrder: 2,
    active: true,
  },
  {
    id: 'cf-ghl-cust-3',
    companyId: 't-ghl-01',
    module: 'customers',
    fieldKey: 'relationshipManager',
    label: 'Relationship Manager',
    fieldType: 'text',
    required: false,
    defaultValue: 'Vikram Malhotra',
    displayOrder: 3,
    active: true,
  },

  // Jamin Bazaar - Customers
  {
    id: 'cf-jam-cust-1',
    companyId: 't-jamin-02',
    module: 'customers',
    fieldKey: 'preferredPaymentBank',
    label: 'Preferred Payment Bank',
    fieldType: 'text',
    required: false,
    defaultValue: 'HDFC Home Loans',
    displayOrder: 1,
    active: true,
  },
  {
    id: 'cf-jam-cust-2',
    companyId: 't-jamin-02',
    module: 'customers',
    fieldKey: 'advocateAssigned',
    label: 'Advocate Assigned',
    fieldType: 'text',
    required: false,
    defaultValue: 'M.K. Associates',
    displayOrder: 2,
    active: true,
  },
];
