import { Customer } from '../types';

export const INITIAL_CUSTOMERS: Customer[] = [
  // GHL Customers
  {
    id: 'cust-ghl-01',
    companyId: 't-ghl-01',
    name: 'Venkatraman Narayanan',
    phone: '+91 98450 99887',
    email: 'v.narayanan@apexholdings.sg',
    status: 'VIP',
    assignedAgentId: 'usr-ghl-admin',
    assignedAgentName: 'Vikram Malhotra',
    location: 'Sadashivanagar, Bengaluru',
    lastContacted: 'Yesterday, 04:15 PM',
    openDealsCount: 1,
    totalValue: 45000000,
    createdAt: '2026-01-15',
    notes: 'Chairman of Singapore-based family office. Invested in Phase 1 warehousing asset.',
    customFields: {
      investorType: 'Family Office / Institutional',
      totalAUMCommitted: '₹4.5 Cr',
      relationshipManager: 'Vikram Malhotra',
    },
  },
  {
    id: 'cust-ghl-02',
    companyId: 't-ghl-01',
    name: 'Suresh Kumar',
    phone: '+91 98450 11223',
    email: 'suresh.k@infraventure.in',
    status: 'Active',
    assignedAgentId: 'usr-ghl-exec',
    assignedAgentName: 'Ananya Iyer',
    location: 'Jayanagar, Bengaluru',
    lastContacted: 'Today, 10:45 AM',
    openDealsCount: 1,
    totalValue: 20000000,
    createdAt: '2026-02-01',
    notes: 'Managing Director of regional infrastructure logistics firm. Evaluating Pre-Leased Office Asset.',
    customFields: {
      investmentCapacity: '₹1.5 Cr – ₹3 Cr',
      preferredAssetClass: 'Commercial Pre-Leased',
    },
  },
  {
    id: 'cust-ghl-03',
    companyId: 't-ghl-01',
    name: 'Moorthi Ramanathan',
    phone: '+91 98800 44556',
    email: 'moorthi@chennaienterprises.com',
    status: 'Active',
    assignedAgentId: 'usr-ghl-exec',
    assignedAgentName: 'Ananya Iyer',
    location: 'R.A. Puram, Chennai',
    lastContacted: 'Yesterday, 03:00 PM',
    openDealsCount: 1,
    totalValue: 40000000,
    createdAt: '2026-02-20',
    notes: 'High net-worth private client. Interested in warehousing logistics tranches.',
    customFields: {
      investmentCapacity: '₹3 Cr – ₹5 Cr',
      preferredAssetClass: 'Warehousing Logistics',
    },
  },
  {
    id: 'cust-ghl-04',
    companyId: 't-ghl-01',
    name: 'Mukesh Ambani Group Holdings',
    phone: '+91 99200 88990',
    email: 'mandates@rilholdings.in',
    status: 'VIP',
    assignedAgentId: 'usr-ghl-exec',
    assignedAgentName: 'Ananya Iyer',
    location: 'Bandra Kurla Complex, Mumbai',
    lastContacted: '2 days ago',
    openDealsCount: 1,
    totalValue: 250000000,
    createdAt: '2026-02-22',
    notes: 'Institutional capital mandate for commercial office assets in prime corridors.',
    customFields: {
      investmentCapacity: '₹25 Cr+',
      preferredAssetClass: 'Commercial Pre-Leased Office',
    },
  },
  {
    id: 'cust-ghl-05',
    companyId: 't-ghl-01',
    name: 'Dr. Rajesh Nambiar',
    phone: '+91 98452 77889',
    email: 'rajesh.nambiar@meditech.org',
    status: 'VIP',
    assignedAgentId: 'usr-ghl-exec',
    assignedAgentName: 'Ananya Iyer',
    assignedIrmId: 'irm-01',
    assignedIrmName: 'Arun Kumar',
    assignedIrmAt: '2026-02-25',
    location: 'Koramangala, Bengaluru',
    lastContacted: 'Yesterday, 11:15 AM',
    openDealsCount: 1,
    totalValue: 75000000,
    createdAt: '2026-01-28',
    notes: 'Active investor assigned to Arun Kumar for fund allocation.',
    customFields: {
      investmentCapacity: '₹5 Cr – ₹10 Cr',
      preferredAssetClass: 'Fintech Hub Pre-Leased',
    },
  },

  // Jamin Customers
  {
    id: 'cust-jam-01',
    companyId: 't-jamin-02',
    name: 'Siddharth Rao',
    phone: '+91 99001 77665',
    email: 'siddharth.rao@accenture.com',
    status: 'Active',
    assignedAgentId: 'usr-jamin-exec',
    assignedAgentName: 'Pooja Hegde',
    location: 'HSR Layout, Bengaluru',
    lastContacted: '2 days ago',
    openDealsCount: 1,
    totalValue: 7200000,
    createdAt: '2026-02-10',
    notes: 'Completed site visit on Feb 22. Placed booking token for Greenfield Meadows Plot #22.',
    customFields: {
      preferredPaymentBank: 'HDFC Home Loans',
      advocateAssigned: 'M.K. Associates',
    },
  },
  {
    id: 'cust-jam-02',
    companyId: 't-jamin-02',
    name: 'Priya Sharma',
    phone: '+91 91234 56780',
    email: 'priya.sharma@techcorp.in',
    status: 'Active',
    assignedAgentId: 'usr-jamin-exec',
    assignedAgentName: 'Pooja Hegde',
    location: 'Hyderabad',
    lastContacted: 'Yesterday, 02:30 PM',
    openDealsCount: 0,
    totalValue: 0,
    createdAt: '2026-09-25',
    notes: 'Inquired for farmland investment near Erode / Coimbatore corridor.',
    customFields: {
      preferredPaymentBank: 'SBI Home Finance',
      advocateAssigned: 'M.K. Associates',
    },
  },
  {
    id: 'cust-jam-03',
    companyId: 't-jamin-02',
    name: 'Ramesh Kumar',
    phone: '+91 64646 46446',
    email: 'ramesh.kumar@gmail.com',
    status: 'Active',
    assignedAgentId: 'usr-jamin-exec',
    assignedAgentName: 'Pooja Hegde',
    location: 'Hyderabad',
    lastContacted: 'Just now',
    openDealsCount: 1,
    totalValue: 5500000,
    createdAt: '2026-09-26',
    notes: 'Looking at Varapatty layout plots for retirement home.',
    customFields: {
      preferredPaymentBank: 'HDFC Home Loans',
      advocateAssigned: 'M.K. Associates',
    },
  },
];
