import { Tenant, User, Role, IrmProfile } from '../types';
import { FEATURES } from '../constants/features';
import { PERMISSIONS } from '../constants/permissions';

export const TENANTS: Record<string, Tenant> = {
  ghl: {
    id: 't-ghl-01',
    name: 'GHL India Ventures',
    slug: 'ghl',
    brandColor: '#ef4444',
    logo: '/og-image -GHL Ventures.png',
    tagline: 'Institutional Wealth & Real Estate Investment Advisory',
    enabledFeatures: [
      FEATURES.LEADS,
      FEATURES.CUSTOMERS,
      FEATURES.DEALS,
      FEATURES.FOLLOWUPS,
      FEATURES.CALLS,
      FEATURES.CALL_RECORDING,
      FEATURES.CALL_TRANSCRIPTION,
      FEATURES.INVESTORS,
      FEATURES.CONSULTATIONS,
      FEATURES.INVESTMENT_OPPORTUNITIES,
      FEATURES.REPORTS,
      FEATURES.USERS,
      FEATURES.ROLES,
      FEATURES.COMPANY_SETTINGS,
      FEATURES.AUDIT_LOGS,
      FEATURES.CHAT,
    ],
    timezone: 'Asia/Kolkata (IST)',
    currency: '₹ INR',
    businessHours: '09:30 AM - 07:00 PM IST',
    status: 'Active',
  },
  jamin: {
    id: 't-jamin-02',
    name: 'Jamin Bazaar',
    slug: 'jamin',
    brandColor: '#e10600',
    logo: '/jamin-logo.png',
    tagline: 'Premium Plotted Enclaves & Farmland Communities',
    enabledFeatures: [
      FEATURES.LEADS,
      FEATURES.CUSTOMERS,
      FEATURES.DEALS,
      FEATURES.FOLLOWUPS,
      FEATURES.CALLS,
      FEATURES.CALL_RECORDING,
      FEATURES.CALL_TRANSCRIPTION,
      FEATURES.PROPERTIES,
      FEATURES.SITE_VISITS,
      FEATURES.BOOKINGS,
      FEATURES.REPORTS,
      FEATURES.USERS,
      FEATURES.ROLES,
      FEATURES.COMPANY_SETTINGS,
      FEATURES.AUDIT_LOGS,
      FEATURES.CHAT,
    ],
    timezone: 'Asia/Kolkata (IST)',
    currency: '₹ INR',
    businessHours: '09:00 AM - 06:30 PM IST',
    status: 'Active',
  },
};

export const ROLES: Record<string, Role> = {
  super_admin: {
    id: 'role-super',
    name: 'Super Admin',
    code: 'super_admin',
    permissions: Object.values(PERMISSIONS),
  },
  company_admin: {
    id: 'role-cadmin',
    name: 'Company Admin',
    code: 'company_admin',
    permissions: [
      PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_UPDATE, PERMISSIONS.LEADS_DELETE, PERMISSIONS.LEADS_ASSIGN, PERMISSIONS.LEADS_EXPORT, PERMISSIONS.LEADS_IMPORT, PERMISSIONS.LEADS_CONVERT,
      PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_UPDATE, PERMISSIONS.CUSTOMERS_DELETE,
      PERMISSIONS.DEALS_VIEW, PERMISSIONS.DEALS_CREATE, PERMISSIONS.DEALS_UPDATE, PERMISSIONS.DEALS_DELETE,
      PERMISSIONS.CALLS_MAKE, PERMISSIONS.CALLS_RECEIVE, PERMISSIONS.CALLS_VIEW, PERMISSIONS.CALLS_RECORDINGS_PLAY,
      PERMISSIONS.FOLLOWUPS_VIEW, PERMISSIONS.FOLLOWUPS_CREATE, PERMISSIONS.FOLLOWUPS_UPDATE,
      PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.PROPERTIES_UPDATE, PERMISSIONS.SITE_VISITS_VIEW, PERMISSIONS.SITE_VISITS_CREATE, PERMISSIONS.BOOKINGS_VIEW, PERMISSIONS.BOOKINGS_CREATE,
      PERMISSIONS.INVESTORS_VIEW, PERMISSIONS.INVESTORS_CREATE, PERMISSIONS.CONSULTATIONS_VIEW, PERMISSIONS.CONSULTATIONS_CREATE, PERMISSIONS.OPPORTUNITIES_VIEW, PERMISSIONS.OPPORTUNITIES_CREATE,
      PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
      PERMISSIONS.USERS_VIEW, PERMISSIONS.USERS_MANAGE, PERMISSIONS.ROLES_VIEW, PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_UPDATE, PERMISSIONS.AUDIT_VIEW,
      PERMISSIONS.CHAT_VIEW, PERMISSIONS.CHAT_SEND,
    ],
  },
  sales_manager: {
    id: 'role-mgr',
    name: 'Sales Manager',
    code: 'sales_manager',
    permissions: [
      PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_UPDATE, PERMISSIONS.LEADS_ASSIGN, PERMISSIONS.LEADS_EXPORT, PERMISSIONS.LEADS_CONVERT,
      PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_UPDATE,
      PERMISSIONS.DEALS_VIEW, PERMISSIONS.DEALS_CREATE, PERMISSIONS.DEALS_UPDATE,
      PERMISSIONS.CALLS_MAKE, PERMISSIONS.CALLS_RECEIVE, PERMISSIONS.CALLS_VIEW, PERMISSIONS.CALLS_RECORDINGS_PLAY,
      PERMISSIONS.FOLLOWUPS_VIEW, PERMISSIONS.FOLLOWUPS_CREATE, PERMISSIONS.FOLLOWUPS_UPDATE,
      PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.PROPERTIES_UPDATE, PERMISSIONS.SITE_VISITS_VIEW, PERMISSIONS.SITE_VISITS_CREATE, PERMISSIONS.BOOKINGS_VIEW, PERMISSIONS.BOOKINGS_CREATE,
      PERMISSIONS.INVESTORS_VIEW, PERMISSIONS.INVESTORS_CREATE, PERMISSIONS.CONSULTATIONS_VIEW, PERMISSIONS.CONSULTATIONS_CREATE, PERMISSIONS.OPPORTUNITIES_VIEW, PERMISSIONS.OPPORTUNITIES_CREATE,
      PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
      PERMISSIONS.USERS_VIEW,
      PERMISSIONS.CHAT_VIEW, PERMISSIONS.CHAT_SEND,
    ],
  },
  sales_executive: {
    id: 'role-exec',
    name: 'Sales Executive',
    code: 'sales_executive',
    permissions: [
      PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_UPDATE, PERMISSIONS.LEADS_CONVERT,
      PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_UPDATE,
      PERMISSIONS.DEALS_VIEW, PERMISSIONS.DEALS_CREATE, PERMISSIONS.DEALS_UPDATE,
      PERMISSIONS.CALLS_MAKE, PERMISSIONS.CALLS_RECEIVE, PERMISSIONS.CALLS_VIEW,
      PERMISSIONS.FOLLOWUPS_VIEW, PERMISSIONS.FOLLOWUPS_CREATE, PERMISSIONS.FOLLOWUPS_UPDATE,
      PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.SITE_VISITS_VIEW, PERMISSIONS.SITE_VISITS_CREATE, PERMISSIONS.BOOKINGS_VIEW, PERMISSIONS.BOOKINGS_CREATE,
      PERMISSIONS.INVESTORS_VIEW, PERMISSIONS.INVESTORS_CREATE, PERMISSIONS.CONSULTATIONS_VIEW, PERMISSIONS.CONSULTATIONS_CREATE, PERMISSIONS.OPPORTUNITIES_VIEW, PERMISSIONS.OPPORTUNITIES_CREATE,
      PERMISSIONS.REPORTS_VIEW,
      PERMISSIONS.CHAT_VIEW, PERMISSIONS.CHAT_SEND,
    ],
  },
  irm: {
    id: 'role-irm',
    name: 'IRM',
    code: 'irm',
    permissions: [
      PERMISSIONS.LEADS_VIEW,
      PERMISSIONS.FOLLOWUPS_VIEW,
      PERMISSIONS.DEALS_VIEW,
      PERMISSIONS.INVESTORS_VIEW,
      PERMISSIONS.INVESTORS_EDIT,
      PERMISSIONS.INVESTORS_CREATE,
      PERMISSIONS.CONSULTATIONS_VIEW,
      PERMISSIONS.CONSULTATIONS_EDIT,
      PERMISSIONS.CONSULTATIONS_CREATE,
      PERMISSIONS.OPPORTUNITIES_VIEW,
      PERMISSIONS.OPPORTUNITIES_EDIT,
      PERMISSIONS.OPPORTUNITIES_CREATE,
      PERMISSIONS.CALL_CENTER,
      PERMISSIONS.CALL_HISTORY,
      PERMISSIONS.REPORTS_VIEW,
      PERMISSIONS.NOTIFICATIONS_VIEW,
      PERMISSIONS.CHAT,
      PERMISSIONS.SMARTY_AI,
      PERMISSIONS.CALL_SETTINGS,
      PERMISSIONS.PROFILE,
    ],
  },
};

export const USERS: User[] = [
  {
    id: 'usr-super-01',
    name: 'Alex Rivera (Super Admin)',
    email: 'alex@nexusplatform.io',
    phone: '+91 98800 11000',
    role: ROLES.super_admin,
    status: 'Active',
    lastLogin: 'Today, 02:15 PM',
  },
  {
    id: 'usr-ghl-admin',
    name: 'Vikram Malhotra',
    email: 'vikram@ghlindiatrust.com',
    phone: '+91 98450 22334',
    role: ROLES.company_admin,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Today, 01:45 PM',
  },
  {
    id: 'usr-ghl-exec',
    name: 'Ananya Iyer',
    email: 'ananya@ghlindiatrust.com',
    phone: '+91 97420 55667',
    role: ROLES.sales_executive,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Today, 11:30 AM',
  },
  {
    id: 'usr-ghl-irm',
    name: 'Rohan Varma',
    email: 'rohan.varma@ghlindiatrust.com',
    phone: '+91 98110 77889',
    role: ROLES.irm,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Today, 10:00 AM',
    designation: 'Investor Relationship Manager',
  },
  {
    id: 'usr-ghl-exec-02',
    name: 'Priya Sharma',
    email: 'priya@ghlindiatrust.com',
    phone: '+91 98450 66778',
    role: ROLES.sales_executive,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Today, 09:45 AM',
  },
  {
    id: 'usr-ghl-exec-03',
    name: 'Rahul Verma',
    email: 'rahul@ghlindiatrust.com',
    phone: '+91 98450 77889',
    role: ROLES.sales_executive,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Today, 09:15 AM',
  },
  {
    id: 'usr-ghl-irm-02',
    name: 'Meera Nair',
    email: 'meera@ghlindiatrust.com',
    phone: '+91 98450 88990',
    role: ROLES.irm,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Today, 10:30 AM',
    designation: 'Senior IRM Partner',
  },
  {
    id: 'usr-ghl-irm-03',
    name: 'Sameer Joshi',
    email: 'sameer@ghlindiatrust.com',
    phone: '+91 98450 99001',
    role: ROLES.irm,
    companyId: 't-ghl-01',
    companySlug: 'ghl',
    companyName: 'GHL India Ventures',
    status: 'Active',
    lastLogin: 'Yesterday, 04:00 PM',
    designation: 'Institutional IRM Partner',
  },
  {
    id: 'usr-jamin-admin',
    name: 'Kavita Rao',
    email: 'kavita@jaminbazaar.com',
    phone: '+91 98860 33445',
    role: ROLES.company_admin,
    companyId: 't-jamin-02',
    companySlug: 'jamin',
    companyName: 'Jamin Bazaar',
    status: 'Active',
    lastLogin: 'Today, 02:00 PM',
  },
  {
    id: 'usr-jamin-exec',
    name: 'Pooja Hegde',
    email: 'pooja@jaminbazaar.com',
    phone: '+91 99160 44889',
    role: ROLES.sales_executive,
    companyId: 't-jamin-02',
    companySlug: 'jamin',
    companyName: 'Jamin Bazaar',
    status: 'Active',
    lastLogin: 'Today, 10:15 AM',
  },
  {
    id: 'usr-jamin-exec-02',
    name: 'Vikram Malhotra',
    email: 'vikram@jaminbazaar.com',
    phone: '+91 98451 99882',
    role: ROLES.sales_executive,
    companyId: 't-jamin-02',
    companySlug: 'jamin',
    companyName: 'Jamin Bazaar',
    status: 'Active',
    lastLogin: 'Today, 11:00 AM',
  },
  {
    id: 'usr-jamin-exec-03',
    name: 'Suresh Kumar',
    email: 'suresh@jaminbazaar.com',
    phone: '+91 97410 88776',
    role: ROLES.sales_executive,
    companyId: 't-jamin-02',
    companySlug: 'jamin',
    companyName: 'Jamin Bazaar',
    status: 'Active',
    lastLogin: 'Today, 09:30 AM',
  },
];

export const MOCK_AGENTS = [
  { id: 1, name: 'Ram' },
  { id: 2, name: 'Sam' },
  { id: 3, name: 'Kishore' },
  { id: 4, name: 'Ray' },
  { id: 5, name: 'Kumar' },
  { id: 6, name: 'Suresh' },
  { id: 7, name: 'Vishnu' },
];

export const MOCK_IRMS: IrmProfile[] = [
  {
    id: 'irm-01',
    name: 'Arun Kumar',
    experience: '5 Years',
    experienceYears: 5,
    experienceLevel: 'Experienced',
    performance: 92,
    status: 'Available',
    email: 'arun.kumar@ghlindiatrust.com',
    phone: '+91 98450 11223',
  },
  {
    id: 'irm-02',
    name: 'Ananya Iyer',
    experience: '4 Years',
    experienceYears: 4,
    experienceLevel: 'Experienced',
    performance: 95,
    status: 'Available',
    email: 'ananya.iyer@ghlindiatrust.com',
    phone: '+91 97420 55667',
  },
  {
    id: 'irm-03',
    name: 'Rohan Mehta',
    experience: '3 Years',
    experienceYears: 3,
    experienceLevel: 'Mid-Level',
    performance: 89,
    status: 'Busy',
    email: 'rohan.mehta@ghlindiatrust.com',
    phone: '+91 98110 77889',
  },
  {
    id: 'irm-04',
    name: 'Priya Nair',
    experience: '2 Years',
    experienceYears: 2,
    experienceLevel: 'Mid-Level',
    performance: 91,
    status: 'Available',
    email: 'priya.nair@ghlindiatrust.com',
    phone: '+91 98220 33445',
  },
  {
    id: 'irm-05',
    name: 'Karthik Sundaram',
    experience: '1 Year',
    experienceYears: 1,
    experienceLevel: 'Fresher',
    performance: 88,
    status: 'Available',
    email: 'karthik.s@ghlindiatrust.com',
    phone: '+91 99001 88776',
  },
];
